package com.lightframe.monitor;
/** Geometry across phone, split window and tablet; metric scales retain their meaning. */
public final class ChartLayoutTests {
 private static int checks;private static void ok(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}private static void eq(double a,double b,String s){ok(Math.abs(a-b)<1e-8,s+" actual="+a+" expected="+b);}
 public static void main(String[] args){
  for(String key:new String[]{"cpuPct","gpuPct","batteryPct"}){ChartAxis a=ChartAxis.of(key,34.3,98.5);eq(a.min,0,key+" starts at zero");eq(a.max,100,key+" percent full scale");eq(a.fraction(70.7),.707,key+" observed 70.7 remains 70.7% of axis");ok(a.ticks.length==5&&a.label(a.ticks[1]).equals("25"),key+" explicit numeric ticks");ChartAxis out=ChartAxis.of(key,-5,125);ok(out.outOfRange,key+" abnormal raw values visibly flagged");}
  ChartAxis fps=ChartAxis.of("fps",0,60.6);eq(fps.min,0,"FPS zero baseline");ok(fps.max>=60.6,"FPS actual upper bound");ChartAxis fast=ChartAxis.of("fps",59,240.5);ok(fast.max>=240.5,"FPS above configured 165 not cropped");ChartAxis core=ChartAxis.of("monitorCpuPct",0,180);ok(core.max>=180,"single-core-equivalent CPU may exceed 100");
  for(String key:new String[]{"fps","gpuMHz","ramUsedMB","frameMs","batteryC","powerW"})for(double[] values:new double[][]{{0,0},{Double.NaN,Double.NaN},{35,35}}){ChartAxis a=ChartAxis.of(key,values[0],values[1]);ok(Double.isFinite(a.min)&&Double.isFinite(a.max)&&a.max>a.min,key+" empty/constant finite range");for(double tick:a.ticks)ok(Double.isFinite(tick),key+" finite ticks");}
  ChartAxis spike=ChartAxis.of("frameMs",6.9,849.8);eq(spike.min,0,"frame interval zero baseline");ok(spike.max>=849.8,"849.8ms recorded spike retained");ChartAxis charging=ChartAxis.of("currentMA",-850,-100);ok(charging.min<=-850&&charging.max>=0,"negative charging current retained");ChartAxis temperature=ChartAxis.of("cpuC",34,42);ok(temperature.min<=34&&temperature.max>=42,"temperature adaptive with explicit scale");
  int[][] windows={{336,700},{616,220},{256,500},{1176,680},{576,900},{900,500}};float[] fonts={1,1.4f,2};
  for(int[] w:windows)for(float font:fonts){double statWidth=118*font;int height=ChartGeometry.recommendedHeight(w[0],w[1],1,font,statWidth);ChartGeometry g=ChartGeometry.layout(w[0],height,1,font,44*font,statWidth);
   ok(g.plotLeft>g.padding&&g.plotRight<w[0],"Y ticks reserved inside window "+w[0]+" font="+font);ok(g.plotHeight()>=6*14*font,"six Y labels have legible spacing");ok(g.titleBaseline<g.cursorBaseline&&g.cursorBaseline<g.statsTop&&g.statsTop+g.statsRows*g.statsLine<g.plotTop,"header rows separated");ok(g.tickBaseline<height,"time labels within chart");
   eq(g.fraction(g.plotLeft),0,"left tick maps to first time");eq(g.fraction(g.plotRight),1,"right tick maps to last time");eq(g.fraction(g.x(.4)),.4,"click and rendered X agree");eq(g.panSeconds(g.plotWidth()/4,40),-10,"drag uses actual plot width");eq(g.y(.707),g.plotBottom-.707*g.plotHeight(),"percent uses actual plot height");ok(!g.inPlot(0,0)&&g.inPlot(g.x(.4),g.y(.5)),"headers are not selectable plot area");
  }
  ChartGeometry phone=ChartGeometry.layout(336,300,1,1,32,110),png=ChartGeometry.layout(1136,650,2,2,64,220);eq(phone.fraction(phone.x(.7)),.7,"phone touch before PNG");eq(png.fraction(png.x(.7)),.7,"PNG has independent geometry");eq(phone.fraction(phone.x(.7)),.7,"PNG geometry cannot alter phone touch");
  ChartGeometry highDpi=ChartGeometry.layout(1008,900,3,3,96,330),wide=ChartGeometry.layout(1176,450,1,1,32,110);eq(highDpi.plotLeft,phone.plotLeft*3,"density scales gutter uniformly");eq(highDpi.plotTop,phone.plotTop*3,"density scales header uniformly");eq(highDpi.plotBottom,phone.plotBottom*3,"density scales plot uniformly");eq(highDpi.fraction(highDpi.x(.37)),phone.fraction(phone.x(.37)),"touch position independent of DPI");eq(wide.titleBaseline,phone.titleBaseline,"wider aspect does not stretch title size");eq(wide.cursorBaseline,phone.cursorBaseline,"wider aspect does not stretch selected-value line");eq(phone.fraction(phone.plotLeft-100),0,"pinch focus left of actual plot clamps");eq(phone.fraction(phone.plotRight+100),1,"pinch focus right of actual plot clamps");
  ok(ChartGeometry.tickCount(220,65,10)==3,"narrow tick count adapts");ok(ChartGeometry.tickCount(1000,65,10)==7,"tablet tick count remains bounded");ok(!ChartGeometry.timeLabel(.123,.01).equals(ChartGeometry.timeLabel(.124,.01)),"subsecond ticks preserve milliseconds");ok(!ChartGeometry.timeLabel(.1234,.0001).equals(ChartGeometry.timeLabel(.1235,.0001)),"submillisecond zoom ticks stay distinct");ok(ChartGeometry.timeLabel(90061,10).equals("25:01:01"),"long history does not wrap at 24h");
  System.out.println(checks+" chart layout/axis checks passed");
 }
}
