package com.lightframe.monitor;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;
public final class CoreTests{
 static int checks;static void ok(boolean b,String name){checks++;if(!b)throw new AssertionError(name);}static void eq(double a,double b,String name){ok(Math.abs(a-b)<1e-6,name+" got="+a+" expected="+b);}static void missing(double a,String name){ok(Double.isNaN(a),name);}
 public static void main(String[] args)throws Exception{
  missing(Numbers.first(null),"unknown is missing");eq(Numbers.temp("42000"),42,"millidegrees");eq(Numbers.temp("34.5"),34.5,"degrees");missing(Numbers.temp("-127000"),"invalid thermal sentinel");missing(Numbers.percent("130"),"out of range load");eq(Numbers.busy("20 80"),25,"busy total");missing(Numbers.busy("0 0"),"zero denominator");
  eq(Numbers.gedFreq("3 950000"),950,"GED index excluded");eq(Numbers.gedFreq("current_freq: 750000"),750,"named GED field");missing(Numbers.gedFreq("index 3, volt 900"),"unknown GED format");eq(Numbers.mtkFreq("[GPU OPP] idx: 2, freq: 600000, volt: 800\n[STACK OPP] idx: 3, freq: 900000, volt: 900"),900,"MTK stack priority");missing(Numbers.mtkFreq("idx: 3, volt: 800"),"MTK no assumed first integer");
  eq(Numbers.gedModuleLoad("67\n","1\n"),67,"GED module percentage");eq(Numbers.gedModuleLoad("0\n","1\n"),0,"GED enabled idle zero is real");missing(Numbers.gedModuleLoad("0\n","0\n"),"GED disabled zero is unavailable");missing(Numbers.gedModuleLoad("67\n","0\n"),"GED disabled driver rejected");eq(Numbers.gedModuleLoad("100\n",null),100,"GED enable node can be unavailable");missing(Numbers.gedModuleLoad(null,"1"),"GED missing read");missing(Numbers.gedModuleLoad("101","1"),"GED out of range");missing(Numbers.gedModuleLoad("-1","1"),"GED negative load");missing(Numbers.gedModuleLoad("20 5 75","1"),"GED module does not accept HAL triple");missing(Numbers.gedModuleLoad("error 13","1"),"GED malformed read rejected");
  long[] cpu=Numbers.cpu("cpu 1 2 3 4 5 6 7 8 1000 2000\ncpu0 0");ok(cpu[0]==36&&cpu[1]==9,"guest excluded");eq(Numbers.cpuPct(new long[]{100,50},new long[]{200,70}),80,"CPU deltas");missing(Numbers.cpuPct(null,cpu),"CPU first read");missing(Numbers.cpuPct(cpu,cpu),"CPU zero interval");eq(Numbers.mem("MemTotal: 2048 kB\nMemAvailable: 1024 kB","MemTotal"),2,"memory unit");missing(Numbers.mem("other: 4","MemTotal"),"missing memory field");
  long[] present=Numbers.present("8333333\n1 300 3\n1 100 3\n1 300 3\n1 9223372036854775807 3\n1 0 3\ncorrupt");ok(Arrays.equals(present,new long[]{100,300}),"present second column, dedup, pending rejected");
  ok(Numbers.safeNode("/sys/class/gpu/freq"),"sys allowed");ok(!Numbers.safeNode("/sys/../../data/foo"),"traversal rejected");ok(!Numbers.safeNode("/data/foo"),"data path rejected");
  String[] cells={"", "你好", "1,2", "a\"b", ""};ok(Arrays.equals(cells,CsvIndex.parse(CsvIndex.encode(cells))),"CSV leading/trailing/quote/unicode roundtrip");
  FrameStats stats=new FrameStats();long n=2_000_000_000L;missing(stats.fps(n),"no FPS without actual frames");stats.add(n,60);missing(stats.fps(n),"one frame insufficient");for(int i=0;i<60;i++)stats.add(n+=(long)(1e9/60),60);eq(Math.round(stats.fps(n)),60,"rolling measured FPS");ok(stats.count==60,"interval count");eq(stats.fps(n+2_000_000_000L),0,"stale frames decay to zero");
  long floor=n+3_000_000_000L;stats.discontinuity(floor);ok(!stats.add(n,60),"old SF buffer ignored after pause");ok(stats.add(floor+10_000_000L,60),"new baseline after pause");missing(stats.frameMs(),"pause not counted as long interval");stats.add(floor+30_000_000L,60);eq(stats.frameMs(),20,"resumed next interval");ok(stats.count==61,"no duplicate or pause interval");
  FrameStats low=new FrameStats();low.add(1_000_000_000L,60);for(int i=1;i<=9;i++)low.add(1_000_000_000L+i*10_000_000L,60);low.add(1_190_000_000L,60);eq(low.low(.1),10,"slowest tail reciprocal");eq(low.percentile(.95),100,"frame time P95");eq(low.percentile(.5),10,"frame time median");ok(low.longFrames==1&&low.bigLongFrames==1,"long frames marked by target budget");
  Path tmp=Files.createTempFile("lightframe-check",".csv");try(Writer w=new OutputStreamWriter(new FileOutputStream(tmp.toFile()),StandardCharsets.UTF_8)){w.write("\uFEFFelapsed_s,fps,cpuPct,paused,note\n");for(int i=0;i<10001;i++)w.write(CsvIndex.encode(new Object[]{i*.25,i==7999?240:i==7777?-10:i%200==0?"":60,i%100,i==128,"中文,\"值\" #"+i})+"\n");}
  try(CsvIndex index=new CsvIndex(tmp.toFile())){ok(index.count==10001,"every original row retained");ok(index.header[0].equals("elapsed_s"),"BOM stripped");ok(index.row(128)[4].equals("中文,\"值\" #128"),"sparse boundary row unicode");eq(index.value(index.row(7999),"fps"),240,"raw spike inspectable");missing(index.value(index.row(8000),"fps"),"raw missing retained");ok(index.nearest(31.999)==128,"nearest across sparse block");ok(index.nearest(-100)==0&&index.nearest(100000)==10000,"nearest ends clamped");ok(index.nearest(1777.25)==7109,"exact row selected by time");ChartData d=ChartData.load(index,new String[]{"fps"})[0];eq(d.max,240,"chart envelope preserves maximum");eq(d.min,-10,"chart envelope preserves minimum");ok(d.times.length<=9003,"chart memory bounded");ok(index.row(7777)[1].equals("-10"),"chart compaction leaves raw CSV intact");ok(Arrays.stream(d.values).anyMatch(Double::isNaN),"pause and missing break drawing");}
  Files.delete(tmp);System.out.println(checks+" checks passed");
 }
}
