package com.lightframe.monitor;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;
/** Real disk snapshots and inclusive ranges; no Android or mocked index implementation. */
public final class HistoryTests {
 private static int checks;private static void ok(boolean b,String name){checks++;if(!b)throw new AssertionError(name);}private static void eq(double a,double b,String name){ok(Math.abs(a-b)<1e-8,name+" got="+a+" expected="+b);}private static void rejects(Runnable task,String name){boolean rejected=false;try{task.run();}catch(IllegalArgumentException e){rejected=true;}ok(rejected,name);}

 /** Check drawing topology against original rows, independently of the envelope's bucket algorithm. */
 private static ChartData verifyEnvelope(String name,double[] raw,boolean[] paused)throws Exception{
  Path file=Files.createTempFile("lightframe-chart-gaps",".csv");double[] expected=raw.clone();long valid=0;double sum=0,min=Double.POSITIVE_INFINITY,max=Double.NEGATIVE_INFINITY;
  try{
   try(Writer w=new OutputStreamWriter(new FileOutputStream(file.toFile()),StandardCharsets.UTF_8)){w.write("elapsed_s,gpuPct,paused\n");for(int i=0;i<raw.length;i++){boolean pause=paused!=null&&paused[i];w.write(CsvIndex.encode(new Object[]{i/4d,Double.isFinite(raw[i])?raw[i]:"",pause})+"\n");if(pause)expected[i]=Double.NaN;if(Double.isFinite(expected[i])){valid++;sum+=expected[i];min=Math.min(min,expected[i]);max=Math.max(max,expected[i]);}}}
   byte[] before=Files.readAllBytes(file);ChartData d;try(CsvIndex index=new CsvIndex(file.toFile())){d=ChartData.load(index,new String[]{"gpuPct"})[0];}
   ok(d.count==valid,name+" statistics include every original valid row");if(valid==0)ok(Double.isNaN(d.min)&&Double.isNaN(d.max)&&Double.isNaN(d.avg),name+" all-missing statistics remain unavailable");else{eq(d.min,min,name+" exact minimum");eq(d.max,max,name+" exact maximum");eq(d.avg,sum/valid,name+" full-row average");}
   ok(d.times.length<=9003,name+" full view drawing budget");eq(d.end,(raw.length-1)/4d,name+" true record endpoint");
   boolean monotonic=true,originalPoints=true,noBridges=true,noFalseBreaks=true;double lastTime=Double.NEGATIVE_INFINITY;int previous=-1;boolean broken=false;
   for(int i=0;i<d.times.length;i++){double time=d.times[i];if(!Double.isFinite(time)||time<lastTime)monotonic=false;lastTime=time;int row=(int)Math.round(time*4);if(row<0||row>=expected.length||time!=row/4d){originalPoints=false;continue;}double value=d.values[i];if(!Double.isFinite(value)){if(Double.isFinite(expected[row]))originalPoints=false;broken=true;continue;}if(value!=expected[row])originalPoints=false;
    if(previous>=0){boolean actualGap=false;for(int r=previous;r<=row;r++)if(!Double.isFinite(expected[r])){actualGap=true;break;}if(actualGap&&!broken)noBridges=false;if(!actualGap&&broken)noFalseBreaks=false;}previous=row;broken=false;
   }
   ok(monotonic,name+" drawing points stay chronological");ok(originalPoints,name+" values and gap markers use actual raw row times");ok(noBridges,name+" no rendered line crosses missing or paused rows");ok(noFalseBreaks,name+" continuous raw runs have no invented break");ok(Arrays.equals(before,Files.readAllBytes(file)),name+" browsing leaves all raw bytes unchanged");return d;
  }finally{Files.deleteIfExists(file);}
 }
 private static void connection(ChartData d,double first,double second,boolean connected,String name){int a=-1,b=-1;for(int i=0;i<d.times.length;i++)if(Double.isFinite(d.values[i])){if(d.times[i]==first)a=i;if(d.times[i]==second)b=i;}boolean gap=false;if(a>=0&&b>a)for(int i=a+1;i<b;i++)gap|=!Double.isFinite(d.values[i]);ok(a>=0&&b>a&&gap!=connected,name);}
 private static void chartGapTests()throws Exception{
  double[] leading=new double[3001];Arrays.fill(leading,40);leading[0]=Double.NaN;leading[1]=10;leading[2]=20;leading[3]=30;ChartData d=verifyEnvelope("leading mixed bucket",leading,null);connection(d,.25,.5,true,"missing before the first selected point does not disconnect later continuous rows");
  double[] middle=new double[6001];Arrays.fill(middle,40);middle[0]=10;middle[1]=Double.NaN;middle[2]=20;d=verifyEnvelope("internal missing row",middle,null);connection(d,0,.5,false,"two retained extremes separated by a missing row are never connected");
  double[] trailing=new double[6001];Arrays.fill(trailing,40);trailing[0]=10;trailing[1]=20;trailing[2]=Double.NaN;trailing[3]=30;trailing[4]=35;d=verifyEnvelope("trailing mixed bucket",trailing,null);connection(d,.25,.75,false,"gap after one bucket breaks the following valid bucket");
  double[] longGap=new double[6001];Arrays.fill(longGap,40);Arrays.fill(longGap,200,1400,Double.NaN);boolean[] pauses=new boolean[longGap.length];Arrays.fill(pauses,1450,1460,true);verifyEnvelope("long missing span and pauses",longGap,pauses);
  double[] alternating=new double[45001];boolean[] sparsePauses=new boolean[alternating.length];for(int i=0;i<alternating.length;i++){alternating[i]=i%2==0?i%101:Double.NaN;sparsePauses[i]=i%997==0;}verifyEnvelope("many fragmented valid runs including real zero GPU",alternating,sparsePauses);
  double[] empty=new double[4501];Arrays.fill(empty,Double.NaN);verifyEnvelope("entirely missing GPU",empty,null);
  double[] finalGap=new double[3001];Arrays.fill(finalGap,40);finalGap[finalGap.length-1]=Double.NaN;d=verifyEnvelope("missing final row",finalGap,null);ok(Double.isNaN(d.values[d.values.length-1])&&d.times[d.times.length-1]==d.end,"terminal missing span is marked at its original time");
  Path duplicate=Files.createTempFile("lightframe-chart-duplicate-time",".csv");try{
   try(Writer w=new OutputStreamWriter(new FileOutputStream(duplicate.toFile()),StandardCharsets.UTF_8)){w.write("elapsed_s,gpuPct,paused\n");for(int i=0;i<6001;i++)w.write(CsvIndex.encode(new Object[]{i<3?0:i/4d,i==0?80:i==1?"":i==2?10:40,false})+"\n");}
   try(CsvIndex index=new CsvIndex(duplicate.toFile())){d=ChartData.load(index,new String[]{"gpuPct"})[0];ok(d.values[0]==80&&Double.isNaN(d.values[1])&&d.values[2]==10,"equal timestamps retain raw extrema order and the intervening missing row");eq(d.min,10,"duplicate-time minimum remains retained");eq(d.max,80,"duplicate-time maximum remains retained");}
  }finally{Files.deleteIfExists(duplicate);}
 }
 public static void main(String[] args)throws Exception {
  TimeZone old=TimeZone.getDefault();TimeZone.setDefault(TimeZone.getTimeZone("Asia/Shanghai"));try{
   eq(HistoryTime.parse("12.345",false,0),12.345,"exact seconds");eq(HistoryTime.parse("02:03.456",false,0),123.456,"minute input");eq(HistoryTime.parse("01:02:03.456",false,0),3723.456,"hour input");
   long start=new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS",Locale.US).parse("2026-10-01 23:59:59.000").getTime();eq(HistoryTime.parse("2026-10-02 00:00:01.250",true,start),2.25,"absolute date crosses midnight");eq(HistoryTime.parse("00:00:01.250",true,start),2.25,"clock mode next day");
   eq(HistoryTime.parse("00:00:01.1",true,start),2.1,"one fractional digit is 100ms");eq(HistoryTime.parse("00:00:01.12",true,start),2.12,"two fractional digits are 120ms");rejects(()->HistoryTime.parse("00:00:01.1234",true,start),"wall precision beyond stored ms explained");
   rejects(()->HistoryTime.parse("1:60",false,0),"invalid seconds");rejects(()->HistoryTime.parse("NaN",false,0),"NaN rejected");rejects(()->HistoryTime.parse("-1",false,0),"negative elapsed rejected");rejects(()->HistoryTime.parse("2026-02-30 12:00:00",true,start),"invalid calendar date rejected");rejects(()->HistoryTime.parse("12:00:00",true,0),"missing wall start explained");
  }finally{TimeZone.setDefault(old);}
  eq(HistoryTime.normalizeBoundary(5.124,5.1238),5.1238,"rounded-up end snaps to true endpoint");eq(HistoryTime.normalizeBoundary(5.123,5.1232),5.1232,"rounded-down end snaps to true endpoint");eq(HistoryTime.normalizeBoundary(-.0004,5),0,"rounded start below zero accepted");eq(HistoryTime.normalizeBoundary(.0004,5),0,"rounded start above zero snaps");eq(HistoryTime.normalizeBoundary(1.2345678,5),1.2345678,"interior precise value unchanged");eq(HistoryTime.normalizeBoundary(5.0005,5),5,"exact half-ms upper tolerance");rejects(()->HistoryTime.normalizeBoundary(5.000501,5),"significant upper overrun rejected");rejects(()->HistoryTime.normalizeBoundary(-.000501,5),"significant start underrun rejected");rejects(()->HistoryTime.normalizeBoundary(Double.NaN,5),"NaN boundary rejected");eq(HistoryTime.normalizeBoundary(0,.0004),0,"tiny record retains actual zero");eq(HistoryTime.normalizeBoundary(.0004,.0004),.0004,"tiny record retains actual end");
  HistoryViewport viewport=new HistoryViewport(100);viewport.zoom(2,.25);eq(viewport.begin,12.5,"zoom preserves focus");eq(viewport.end,62.5,"zoom half span");viewport.pan(100);eq(viewport.begin,50,"right pan bounded");eq(viewport.end,100,"right end bounded");viewport.pan(-1000);eq(viewport.begin,0,"left pan bounded");eq(viewport.end,50,"pan preserves span");viewport.set(10,20);viewport.zoom(2,.5);eq(viewport.begin,12.5,"explicit range zoom");viewport.reset();eq(viewport.end,100,"reset full");eq(new HistoryViewport(Double.NaN).end,.001,"empty frame CSV cannot poison viewport");rejects(()->viewport.set(10,10),"zero range invalid");
  HistorySelection selection=new HistorySelection();int firstPage=selection.stamp();int jump=selection.request();ok(!selection.current(firstPage),"overview-to-samples default cannot defeat exact time jump");ok(selection.current(jump),"exact jump remains current after rejected default");int charts=selection.stamp();int tap=selection.request();ok(!selection.current(charts)&&selection.current(tap),"slow chart load cannot defeat user point selection");int older=selection.request(),newer=selection.request();ok(!selection.current(older)&&selection.current(newer),"latest point wins out-of-order completion");selection.request();ok(!selection.current(newer),"page change invalidates old detail request");
  Path folder=Files.createTempDirectory("lightframe-history");File csv=folder.resolve("samples.csv").toFile(),frames=folder.resolve("frames.csv").toFile();
  try{
   try(Writer w=new OutputStreamWriter(new FileOutputStream(csv),StandardCharsets.UTF_8)){w.write("\uFEFFelapsed_s,fps,cpuPct,gpuPct,paused,gpuLoadStatus,note\r\n");
    for(int i=0;i<60001;i++){if(i%113==0)w.write("\r\n");double time=i/4d;String fps=i==12345?"240":i==12346?"":i==12347?"-10":"60";w.write(CsvIndex.encode(new Object[]{time,fps,i%100,"",i==12348,"系统拒绝当前授权读取 GPU 节点","中文,\"值\" #"+i})+"\r\n");}
   }
   long originalLength=csv.length();byte[] before=Files.readAllBytes(csv.toPath());long started=System.nanoTime();
   try(CsvIndex index=new CsvIndex(csv)){
    ok(index.count==60001,"large CSV counts all complete nonblank rows");eq(index.firstTime,0,"first indexed time");eq(index.lastTime,15000,"last indexed time");ok(index.header[0].equals("elapsed_s"),"UTF8 BOM handled");
    for(int n:new int[]{0,127,128,255,256,12345,32767,60000}){String[] row=index.row(n);eq(CsvIndex.time(row),n/4d,"buffer and sparse offset "+n);ok(row[6].equals("中文,\"值\" #"+n),"UTF8 quoted raw value "+n);}
    ok(index.nearest(31.999)==128,"nearest sparse boundary");ok(index.nearest(3086.2501)==12345,"nearest exact spike");ok(index.nearest(3086.375)==12345,"equal-distance tie earlier row");ok(index.lowerBound(3086.25)==12345&&index.upperBound(3086.25)==12346,"inclusive exact endpoint");
    ChartData ranged=ChartData.load(index,new String[]{"fps"},3086.25,3087.25)[0];eq(ranged.max,240,"range chart uses raw spike");eq(ranged.min,-10,"range chart does not drop negative raw value");ok(ranged.count==3,"paused and missing not chart statistics");
    HistoryRange stats=HistoryRange.load(index,null,3086.25,3087.25,new String[]{"fps","gpuPct","oldMissingMetric"});ok(stats.rows==5&&stats.pausedRows==1,"interval counts complete rows inclusive");HistoryRange.Metric m=stats.metrics.get("fps");ok(m.valid==3&&m.missing==1&&m.paused==1,"valid missing pause distinct");eq(m.avg,(240-10+60)/3d,"mean from every original value");eq(m.min,-10,"range minimum exact");eq(m.max,240,"range maximum exact");ok(stats.missingReasons.get("gpuPct").equals("系统拒绝当前授权读取 GPU 节点"),"missing GPU displays device status without inventing zero");ok(stats.missingReasons.get("oldMissingMetric").contains("此版本"),"old missing column explained");ok(Double.isNaN(stats.metrics.get("gpuPct").avg),"GPU no numeric samples remains NaN");
    ChartData full=ChartData.load(index,new String[]{"fps"})[0];ok(full.times.length<=9003,"large full view remains bounded");eq(full.max,240,"full envelope preserves rare spike");ok(Arrays.stream(full.values).anyMatch(Double::isNaN),"missing creates drawing break");
    try(Writer w=new OutputStreamWriter(new FileOutputStream(csv,true),StandardCharsets.UTF_8)){w.write("15000.25,90,50,,false,拒绝,新增\r\n15000.5,12");}
    final int[] scanned={0};index.scan((n,row)->scanned[0]++);ok(scanned[0]==60001&&index.count==60001,"append cannot drift snapshot counts");eq(index.value(index.row(12345),"fps"),240,"raw spike remains addressable after chart compaction");
    Thread.currentThread().interrupt();boolean cancelled=false;try{index.scan((n,row)->{});}catch(InterruptedIOException e){cancelled=true;}finally{Thread.interrupted();}ok(cancelled,"obsolete full scan cooperatively cancels");
   }
   try(CsvIndex updated=new CsvIndex(csv)){ok(updated.count==60002,"refresh includes complete append but excludes partial tail");ok(updated.row(60001)[6].equals("新增"),"refreshed UTF8 row exact");}
   ok(Arrays.equals(before,Arrays.copyOf(Files.readAllBytes(csv.toPath()),(int)originalLength)),"history browsing never mutates original raw bytes");
   File duplicate=folder.resolve("duplicate.csv").toFile();Files.write(duplicate.toPath(),"elapsed_s,fps,paused\n1,10,false\n2,20,false\n2,30,false\n2,40,false\n3,50,false\n".getBytes(StandardCharsets.UTF_8));Files.write(frames.toPath(),"elapsed_s,interval_ms\n1.5,10\n2,20\n2.5,30\n".getBytes(StandardCharsets.UTF_8));
   try(CsvIndex index=new CsvIndex(duplicate);CsvIndex fi=new CsvIndex(frames)){ok(index.lowerBound(2)==1&&index.upperBound(2)==4,"all duplicate times included");HistoryRange equal=HistoryRange.load(index,fi,2,2,new String[]{"fps"});ok(equal.rows==3&&equal.frameRows==1,"point interval includes duplicate rows and exact frame");eq(equal.metrics.get("fps").avg,30,"all duplicate values statistics");eq(equal.metrics.get("interval_ms").avg,20,"frame interval raw mean");HistoryRange empty=HistoryRange.load(index,fi,4,5,new String[]{"fps"});ok(empty.rows==0&&Double.isNaN(empty.metrics.get("fps").avg),"empty interval remains missing");}
   for(double endpoint:new double[]{5.1238,5.1232}){
    File boundary=folder.resolve("boundary.csv").toFile();Files.write(boundary.toPath(),("elapsed_s,fps,paused\n0,10,false\n"+endpoint+",99,false\n").getBytes(StandardCharsets.UTF_8));
    try(CsvIndex index=new CsvIndex(boundary)){double displayed=HistoryTime.parse(HistoryTime.elapsed(index.lastTime),false,0),normalized=HistoryTime.normalizeBoundary(displayed,index.lastTime);HistoryRange range=HistoryRange.load(index,null,0,normalized,new String[]{"fps"});ok(range.rows==2,"default displayed interval includes real final row "+endpoint);eq(range.metrics.get("fps").max,99,"final raw metric remains in inclusive interval "+endpoint);eq(normalized,index.lastTime,"inclusive boundary uses CSV precision "+endpoint);}
   }
   chartGapTests();
   System.out.println(checks+" history checks passed; 60001-row snapshot/range/chart checks in "+((System.nanoTime()-started)/1000000)+" ms");
  }finally{File[] files=folder.toFile().listFiles();if(files!=null)for(File f:files)f.delete();folder.toFile().delete();}
 }
}
