package com.lightframe.monitor;
import java.io.*;import java.nio.file.*;import java.util.*;
/** Real private-folder fixtures; never operates on application or device records. */
public final class RecordDeletionTests{
 static int checks;static void ok(boolean b,String name){checks++;if(!b)throw new AssertionError(name);}interface Action{void run()throws Exception;}static void rejects(Action action,String name)throws Exception{try{action.run();throw new AssertionError(name);}catch(IOException expected){checks++;}}
 static void write(Path p,String value)throws IOException{Files.createDirectories(p.getParent());Files.write(p,value.getBytes(java.nio.charset.StandardCharsets.UTF_8));}
 static boolean link(Path path,Path target)throws Exception{try{Files.createSymbolicLink(path,target);return true;}catch(IOException|UnsupportedOperationException denied){if(!System.getProperty("os.name").startsWith("Windows"))throw denied;for(String text:new String[]{path.toString(),target.toString()})if(text.matches(".*[\"%!&|<>].*"))return false;java.lang.Process command=new ProcessBuilder("cmd.exe","/c","mklink","/J",path.toString(),target.toString()).redirectErrorStream(true).start();try(InputStream in=command.getInputStream()){while(in.read()!=-1){}}return command.waitFor()==0;}}
 static void cleanup(Path path)throws IOException{if(!Files.exists(path,LinkOption.NOFOLLOW_LINKS))return;boolean plain=false;try{plain=!Files.isSymbolicLink(path)&&path.toRealPath().equals(path.toAbsolutePath().normalize());}catch(IOException ignored){}if(plain&&Files.isDirectory(path,LinkOption.NOFOLLOW_LINKS))try(DirectoryStream<Path> children=Files.newDirectoryStream(path)){for(Path child:children)cleanup(child);}Files.deleteIfExists(path);}
 public static void main(String[] args)throws Exception{
  Path base=Files.createTempDirectory("lightframe-record-deletion-"),root=base.resolve("sessions"),outside=base.resolve("outside"),active=root.resolve("active");try{
   Files.createDirectories(root);write(outside.resolve("keep.txt"),"outside kept");write(active.resolve("samples.csv"),"active kept");Path a=root.resolve("first record"),b=root.resolve("second");write(a.resolve("samples.csv"),"first original");write(a.resolve("nested/frames.csv"),"frames");write(b.resolve("samples.csv"),"second original");
   rejects(()->RecordDeletion.delete(root.toFile(),active.toFile(),active.toFile()),"active recording refused");ok(Files.readAllBytes(active.resolve("samples.csv")).length>0,"active bytes retained");rejects(()->RecordDeletion.delete(root.toFile(),outside.toFile(),null),"external directory refused");rejects(()->RecordDeletion.delete(root.toFile(),root.resolve("../outside").toFile(),null),"traversal selection refused");rejects(()->RecordDeletion.delete(root.toFile(),root.toFile(),null),"whole sessions root refused");rejects(()->RecordDeletion.delete(root.toFile(),a.resolve("samples.csv").toFile(),null),"single file is not a selected recording");rejects(()->RecordDeletion.delete(root.toFile(),a.resolve("nested").toFile(),null),"nested directory is not a direct recording");ok(Files.readAllBytes(outside.resolve("keep.txt")).length>0&&Files.exists(a.resolve("samples.csv"))&&Files.exists(b.resolve("samples.csv")),"rejected deletions preserve all unrelated data");
   Path alias=root.resolve("external-alias");if(link(alias,outside)){
    rejects(()->RecordDeletion.delete(root.toFile(),alias.toFile(),null),"top-level directory alias cannot escape sessions root");ok(Files.exists(outside.resolve("keep.txt")),"outside link target retained");Files.delete(alias);
    Path guarded=root.resolve("guarded");write(guarded.resolve("a-normal.csv"),"must survive preflight");write(guarded.resolve("nested/b-normal.csv"),"nested retained");Path indirect=guarded.resolve("nested/zzz-link");ok(link(indirect,outside),"inner link fixture created");rejects(()->RecordDeletion.delete(root.toFile(),guarded.toFile(),null),"inner link rejects entire tree before any deletion");ok(Files.exists(guarded.resolve("a-normal.csv"))&&Files.exists(guarded.resolve("nested/b-normal.csv"))&&Files.exists(outside.resolve("keep.txt")),"preflight failure preserves earlier files, nested files and external target");Files.delete(indirect);
    ok(link(indirect,active),"internal target link fixture created");rejects(()->RecordDeletion.delete(root.toFile(),guarded.toFile(),null),"link to an internal active recording also rejects entire tree");ok(Files.exists(active.resolve("samples.csv"))&&Files.exists(guarded.resolve("a-normal.csv")),"internal link cannot delete active record or partially delete selected record");Files.delete(indirect);
    if(!System.getProperty("os.name").startsWith("Windows")){Files.createSymbolicLink(indirect,base.resolve("missing-target"));rejects(()->RecordDeletion.delete(root.toFile(),guarded.toFile(),null),"broken symlink fails preflight too");ok(Files.exists(guarded.resolve("a-normal.csv")),"broken link rejection preserves earlier regular files");Files.delete(indirect);}
   }else System.out.println("Symlink/junction fixtures unavailable on this host; Linux CI must exercise them");
   ok(RecordDeletion.delete(root.toFile(),a.toFile(),active.toFile()),"first selected independent record removed");ok(!Files.exists(a)&&Files.exists(b.resolve("samples.csv")),"first deletion leaves second record intact");ok(RecordDeletion.delete(root.toFile(),b.toFile(),active.toFile()),"second selected independent record removed");ok(!Files.exists(b)&&Files.exists(active.resolve("samples.csv"))&&Files.exists(outside.resolve("keep.txt")),"second deletion preserves active and external records");System.out.println("Record deletion checks: "+checks);
  }finally{cleanup(base);}
 }
}
