package com.lightframe.monitor;
import java.io.IOException;import java.util.*;import org.json.*;
public final class UpdateReleaseTests{
 static int checks;static void ok(boolean v,String name){checks++;if(!v)throw new AssertionError(name);}interface Action{void run()throws Exception;}static void rejects(Action a,String name)throws Exception{try{a.run();throw new AssertionError(name);}catch(IOException expected){checks++;}}
 static JSONObject release(String version)throws Exception{JSONObject r=new JSONObject();r.put("tag_name","v"+version);r.put("draft",false);r.put("prerelease",false);JSONArray assets=new JSONArray();for(String name:Arrays.asList("LightFrame-"+version+"-full.apk","LightFrame-"+version+"-lite.apk","SHA256SUMS.txt")){JSONObject a=new JSONObject();a.put("name",name);a.put("browser_download_url","https://github.com/ggboy6666/LightFrame/releases/download/v"+version+"/"+name);a.put("state","uploaded");a.put("size",1024);assets.put(a);}r.put("assets",assets);return r;}
 public static void main(String[] args)throws Exception{
  JSONObject fixture=release("1.0.1");UpdateRelease full=UpdateRelease.parse(fixture.toString(),"full"),lite=UpdateRelease.parse(fixture.toString(),"lite");ok(full.apkName.equals("LightFrame-1.0.1-full.apk")&&lite.apkName.equals("LightFrame-1.0.1-lite.apk"),"release selects the correct simultaneously published variant");ok(full.newerThan("1.0.0")&&!full.newerThan("1.0.1")&&!full.newerThan("2.0.0"),"only actual newer versions are updates");ok(UpdateRelease.compare("1.10.0","1.9.9")>0&&UpdateRelease.compare("1.0.0","0.2.6")>0,"numeric stable version comparison handles digit lengths and beta-era version");ok(full.releaseUrl.equals("https://github.com/ggboy6666/LightFrame/releases/tag/v1.0.1"),"user-facing link is fixed repository release");
  for(String field:Arrays.asList("draft","prerelease")){JSONObject r=release("1.0.1");r.put(field,true);rejects(()->UpdateRelease.parse(r.toString(),"full"),"nonstable release rejected");}
  for(String tag:Arrays.asList("v1.0","v1.0.1-beta","v01.0.1","v99999999.0.0","v1/0/1")){JSONObject r=release("1.0.1");r.put("tag_name",tag);rejects(()->UpdateRelease.parse(r.toString(),"full"),"malformed or unsafe version rejected");}
  for(String url:Arrays.asList("http://github.com/ggboy6666/LightFrame/releases/download/v1.0.1/LightFrame-1.0.1-full.apk","https://github.com/other/LightFrame/releases/download/v1.0.1/LightFrame-1.0.1-full.apk","https://example.com/update.apk","https://github.com/ggboy6666/LightFrame/releases/download/v1.0.1/../update.apk")){JSONObject r=release("1.0.1");r.getJSONArray("assets").getJSONObject(0).put("browser_download_url",url);rejects(()->UpdateRelease.parse(r.toString(),"full"),"untrusted or mismatched asset URL rejected");}
  for(long size:new long[]{0,-1,UpdateRelease.MAX_APK_BYTES+1L}){JSONObject r=release("1.0.1");r.getJSONArray("assets").getJSONObject(0).put("size",size);rejects(()->UpdateRelease.parse(r.toString(),"full"),"APK download size bounded");}
  ok(full.newerThan("0.2.6"),"existing 0.2.6 full installation migrates to stable numeric version");JSONObject legacy=release("0.2.6");legacy.put("prerelease",true);legacy.getJSONArray("assets").getJSONObject(0).put("name","LightFrame-0.2.6-beta.apk");rejects(()->UpdateRelease.parse(legacy.toString(),"full"),"old single-APK prerelease cannot replace stable full variant");rejects(()->UpdateRelease.parse(legacy.toString(),"lite"),"old full-only beta APK cannot be selected for Lite");
  JSONObject missing=release("1.0.1");missing.put("assets",new JSONArray());rejects(()->UpdateRelease.parse(missing.toString(),"full"),"absent artifacts are not a downloadable release");JSONObject duplicate=release("1.0.1");duplicate.getJSONArray("assets").put(duplicate.getJSONArray("assets").getJSONObject(0));rejects(()->UpdateRelease.parse(duplicate.toString(),"full"),"duplicate variant metadata rejected");rejects(()->UpdateRelease.parse("{","full"),"malformed JSON rejected");rejects(()->UpdateRelease.parse(fixture.toString(),"unknown"),"unknown variant rejected");
  char[] chars=new char[64];Arrays.fill(chars,'a');String digest=new String(chars);String sums=digest+"  "+full.apkName+"\n"+digest+" *"+lite.apkName+"\n";ok(full.checksum(sums).equals(digest)&&lite.checksum(sums).equals(digest),"checksum selects exact variant and supports text or binary sha256sum form");rejects(()->full.checksum(digest+"  wrong.apk\n"),"missing variant checksum rejected");rejects(()->full.checksum(sums+sums),"ambiguous repeated checksum rejected");rejects(()->full.checksum("invalid  "+full.apkName),"invalid SHA-256 format rejected");
  JSONObject nullDigest=release("1.0.1");nullDigest.getJSONArray("assets").getJSONObject(0).put("digest",JSONObject.NULL);ok(UpdateRelease.parse(nullDigest.toString(),"full").checksum(sums).equals(digest),"nullable GitHub digest falls back to mandatory SHA256SUMS verification");
  JSONObject digestRelease=release("1.0.1");digestRelease.getJSONArray("assets").getJSONObject(0).put("digest","sha256:"+digest.toUpperCase(Locale.US));UpdateRelease validated=UpdateRelease.parse(digestRelease.toString(),"full");ok(validated.checksum(sums).equals(digest),"GitHub-provided SHA-256 agrees with downloaded manifest");rejects(()->validated.checksum(sums.replace(digest,digest.replace('a','b'))),"mismatched API and manifest digests rejected");digestRelease.getJSONArray("assets").getJSONObject(0).put("digest","md5:abcd");rejects(()->UpdateRelease.parse(digestRelease.toString(),"full"),"unsupported digest rejected");
  System.out.println("Update release checks: "+checks);
 }
}
