package com.lightframe.monitor;
import android.content.*;import android.database.*;import android.net.Uri;import android.os.*;import android.provider.OpenableColumns;import java.io.*;
public final class ExportProvider extends ContentProvider{
 public boolean onCreate(){return true;}
 public static Uri uri(Context c,File f)throws IOException{String base=c.getFilesDir().getCanonicalPath()+"/sessions/",cache=c.getCacheDir().getCanonicalPath()+"/exports/",p=f.getCanonicalPath();if(!(p.startsWith(base)||p.startsWith(cache)))throw new SecurityException("非法导出路径");return new Uri.Builder().scheme("content").authority("com.lightframe.monitor.export").appendQueryParameter("path",p).build();}
 private File file(Uri uri)throws FileNotFoundException{try{String raw=uri.getQueryParameter("path");if(raw==null)throw new IOException("missing path");File f=new File(raw).getCanonicalFile();String p=f.getPath(),a=getContext().getFilesDir().getCanonicalPath()+"/sessions/",b=getContext().getCacheDir().getCanonicalPath()+"/exports/";if(!p.startsWith(a)&&!p.startsWith(b))throw new IOException("非法路径");if(!f.isFile())throw new IOException("文件不存在");return f;}catch(Exception e){throw new FileNotFoundException(e.toString());}}
 public ParcelFileDescriptor openFile(Uri uri,String mode)throws FileNotFoundException{if(!mode.equals("r"))throw new FileNotFoundException("只读");return ParcelFileDescriptor.open(file(uri),ParcelFileDescriptor.MODE_READ_ONLY);}
 public String getType(Uri u){String p=u.getQueryParameter("path");return p!=null&&p.endsWith(".png")?"image/png":p!=null&&p.endsWith(".csv")?"text/csv":p!=null&&p.endsWith(".txt")?"text/plain":"application/zip";}
 public Cursor query(Uri u,String[] projection,String selection,String[] args,String order){try{File f=file(u);String[] cols=projection==null?new String[]{OpenableColumns.DISPLAY_NAME,OpenableColumns.SIZE}:projection;MatrixCursor c=new MatrixCursor(cols);Object[] v=new Object[cols.length];for(int i=0;i<cols.length;i++)v[i]=cols[i].equals(OpenableColumns.DISPLAY_NAME)?f.getName():cols[i].equals(OpenableColumns.SIZE)?f.length():null;c.addRow(v);return c;}catch(Exception e){return null;}}
 public Uri insert(Uri u,ContentValues v){throw new UnsupportedOperationException();}public int delete(Uri u,String s,String[] a){throw new UnsupportedOperationException();}public int update(Uri u,ContentValues v,String s,String[] a){throw new UnsupportedOperationException();}
}
