package com.lightframe.monitor;
import android.content.*;import android.graphics.*;import android.view.*;
public final class HistoryChart extends View{
 private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);private final Path path=new Path();public final ChartData data;
 private double begin,end,cursor=Double.NaN,cursorValue=Double.NaN;private float downX,downY,lastX;private boolean moved,scaling;private long lastTap;private final ScaleGestureDetector scale;public java.util.function.DoubleConsumer onSelect;
 public HistoryChart(Context c,ChartData d){super(c);data=d;end=Math.max(1,d.end);setContentDescription(Config.label(d.key)+"历史曲线。点选查看完整数据，双指缩放，左右拖动，双击复位。");scale=new ScaleGestureDetector(c,new ScaleGestureDetector.SimpleOnScaleGestureListener(){public boolean onScale(ScaleGestureDetector detector){double span=end-begin,focus=begin+(end-begin)*detector.getFocusX()/Math.max(1,getWidth());double next=Math.max(.1,Math.min(Math.max(1,data.end),span/detector.getScaleFactor()));begin=focus-(focus-begin)*next/span;end=begin+next;clamp();scaling=true;getParent().requestDisallowInterceptTouchEvent(true);invalidate();return true;}});}
 public void select(double t,double value){cursor=t;cursorValue=value;invalidate();}
 private void clamp(){double span=end-begin,full=Math.max(1,data.end);if(begin<0){begin=0;end=span;}if(end>full){end=full;begin=Math.max(0,end-span);}}
 @Override protected void onDraw(Canvas c){render(c,getWidth(),getHeight());}
 public void render(Canvas c,int width,int height){c.save();c.scale(width/450f,height/190f);c.clipRect(0,0,450,190);p.setColor(0xFFE2DFED);c.drawRoundRect(0,0,450,190,6,6,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(12);p.setColor(0xFF676D9C);p.setTextAlign(Paint.Align.LEFT);c.drawText(Config.label(data.key)+" ("+Config.unit(data.key)+")",10,20,p);p.setColor(0xFFD3D0E1);c.drawLine(8,29,442,29,p);p.setTextSize(10);p.setColor(0xFF58566A);c.drawText("min "+Numbers.display(data.min,1),10,44,p);p.setTextAlign(Paint.Align.CENTER);c.drawText("avg "+Numbers.display(data.avg,1),225,44,p);p.setTextAlign(Paint.Align.RIGHT);c.drawText("max "+Numbers.display(data.max,1),440,44,p);p.setTextAlign(Paint.Align.LEFT);
  for(int i=0;i<=4;i++){p.setColor(0xFFD8D4E4);c.drawLine(10,52+i*29,440,52+i*29,p);}double low=data.min,high=data.max;if(high==low){low-=1;high+=1;}if(!Double.isFinite(low)){p.setColor(0xFF767185);p.setTextAlign(Paint.Align.CENTER);c.drawText("未取得此指标",225,104,p);p.setTextAlign(Paint.Align.LEFT);}else{double padding=(high-low)*.08;low-=padding;high+=padding;c.save();c.clipRect(10,50,440,170);path.reset();boolean pen=false;for(int i=0;i<data.times.length;i++){double t=data.times[i],v=data.values[i];if(!Double.isFinite(v)){pen=false;continue;}float x=(float)(10+(t-begin)/(end-begin)*430),y=(float)(168-(v-low)/(high-low)*114);if(pen)path.lineTo(x,y);else{path.moveTo(x,y);pen=true;}}p.setColor(0xFF65709D);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.1f);c.drawPath(path,p);p.setStyle(Paint.Style.FILL);if(Double.isFinite(cursor)&&cursor>=begin&&cursor<=end){float x=(float)(10+(cursor-begin)/(end-begin)*430);p.setColor(0xFF8E8AC2);p.setStrokeWidth(.8f);c.drawLine(x,50,x,170,p);if(Double.isFinite(cursorValue)){float y=(float)(168-(cursorValue-low)/(high-low)*114);c.drawCircle(x,y,3,p);}}c.restore();}
  p.setColor(0xFF6A6478);p.setTextSize(9);for(int i=0;i<5;i++){p.setTextAlign(i==0?Paint.Align.LEFT:i==4?Paint.Align.RIGHT:Paint.Align.CENTER);c.drawText(Config.elapsed(begin+(end-begin)*i/4),10+430*i/4f,183,p);}p.setTextAlign(Paint.Align.LEFT);if(Double.isFinite(cursor)){p.setColor(0xFF656A9D);p.setTextSize(10);p.setTextAlign(Paint.Align.RIGHT);c.drawText(Config.elapsed(cursor)+"  "+Config.format(data.key,cursorValue),440,20,p);p.setTextAlign(Paint.Align.LEFT);}c.restore();
 }
 @Override public boolean onTouchEvent(MotionEvent e){scale.onTouchEvent(e);switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:downX=lastX=e.getX();downY=e.getY();moved=scaling=false;return true;case MotionEvent.ACTION_MOVE:if(!scaling&&e.getPointerCount()==1&&Math.abs(e.getX()-downX)>Math.abs(e.getY()-downY)&&Math.abs(e.getX()-downX)>8){moved=true;getParent().requestDisallowInterceptTouchEvent(true);double delta=(e.getX()-lastX)/Math.max(1,getWidth())*(end-begin);begin-=delta;end-=delta;clamp();invalidate();}lastX=e.getX();return true;case MotionEvent.ACTION_UP:getParent().requestDisallowInterceptTouchEvent(false);if(!moved&&!scaling&&Math.abs(e.getY()-downY)<15){long now=android.os.SystemClock.uptimeMillis();if(now-lastTap<320){begin=0;end=Math.max(1,data.end);invalidate();lastTap=0;}else{lastTap=now;double t=begin+Math.max(0,Math.min(1,(e.getX()/getWidth()-10/450d)/(430/450d)))*(end-begin);if(onSelect!=null)onSelect.accept(t);}performClick();}return true;default:return true;}}
 @Override public boolean performClick(){super.performClick();return true;}
}
