package com.lightframe.monitor;

import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;import java.util.zip.*;import rikka.shizuku.Shizuku;

/** Native Views and Canvas, styled from the user's RakkaRecorder recording. */
public final class MainActivity extends Activity{
 private static final int BG=0xFFF8F5FF,CARD=0xFFE2DFED,INK=0xFF3F3A49,MUTED=0xFF706B82,ACCENT=0xFF656D9E;
 private final Handler ui=new Handler(Looper.getMainLooper());private final ExecutorService io=Executors.newSingleThreadExecutor();
 private LinearLayout root,body,header,nav,content,detail,historyBody,historyTabs;private TextView statusView;private final Map<String,TextView> live=new LinkedHashMap<>();private String shownLive="",page="home";private File session,pendingExport;private CsvIndex sampleIndex,frameIndex;private JSONObject summary;private int tab,generation,selectedRow=-1,selectedFrame=-1,samplePage,framePage;private final ArrayList<HistoryChart> charts=new ArrayList<>();private boolean destroyed;
 private final Runnable refresh=new Runnable(){public void run(){if(page.equals("home")){if(statusView!=null)statusView.setText(MonitorService.status);String s=MonitorService.latest;if(!shownLive.equals(s)){shownLive=s;try{JSONObject j=new JSONObject(s);for(Map.Entry<String,TextView> e:live.entrySet())e.getValue().setText(Config.format(e.getKey(),j.optDouble(e.getKey())));}catch(Exception ignored){}}}ui.postDelayed(this,250);}};
 private final Shizuku.OnRequestPermissionResultListener permission=(code,result)->{if(code==101)toast(result==PackageManager.PERMISSION_GRANTED?"Shizuku 已授权":"未获得 Shizuku 授权");};
 @Override public void onCreate(Bundle saved){super.onCreate(saved);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(0xFFEEEBF6);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});setContentView(root);Shizuku.addRequestPermissionResultListener(permission);if(saved!=null&&saved.getString("export")!=null)pendingExport=new File(saved.getString("export"));showHome();}
 @Override protected void onResume(){super.onResume();ui.removeCallbacks(refresh);ui.post(refresh);}
 @Override protected void onPause(){ui.removeCallbacks(refresh);super.onPause();}
 @Override protected void onDestroy(){destroyed=true;generation++;ui.removeCallbacksAndMessages(null);Shizuku.removeRequestPermissionResultListener(permission);io.execute(()->closeIndexes());io.shutdown();super.onDestroy();}
 @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);if(pendingExport!=null)out.putString("export",pendingExport.getAbsolutePath());}
 private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 private TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
 private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 private void gap(LinearLayout l,int h){l.addView(new View(this),new LinearLayout.LayoutParams(1,dp(h)));}
 private TextView button(String s,Runnable run){TextView t=text(s,13,ACCENT);t.setGravity(Gravity.CENTER);t.setPadding(dp(12),dp(10),dp(12),dp(10));t.setBackground(round(0xFFDCDCF1,18));t.setOnClickListener(v->run.run());t.setMinHeight(dp(40));return t;}
 private void buttons(LinearLayout parent,String a,Runnable ra,String b,Runnable rb){LinearLayout r=row();TextView x=button(a,ra),y=button(b,rb);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(42),1);p.setMargins(0,0,dp(8),0);r.addView(x,p);r.addView(y,new LinearLayout.LayoutParams(0,dp(42),1));parent.addView(r);gap(parent,8);}
 private void shell(String title,String destination,boolean back){page=destination;generation++;root.removeAllViews();live.clear();charts.clear();header=row();header.setPadding(dp(12),0,dp(12),0);TextView h=text(back?"‹":"◈",26,INK);h.setGravity(Gravity.CENTER);h.setContentDescription(back?"返回记录列表":"轻帧");h.setOnClickListener(v->{if(back)showRecords();});header.addView(h,new LinearLayout.LayoutParams(dp(36),dp(50)));header.addView(text(title,17,INK),new LinearLayout.LayoutParams(0,dp(54),1));root.addView(header);body=column();root.addView(body,new LinearLayout.LayoutParams(-1,0,1));nav=row();nav.setBackgroundColor(0xFFEEEBF6);String[] names={"主页","记录","设置"},icons={"⌂","▥","⚙"};for(int i=0;i<3;i++){final int n=i;LinearLayout item=column();item.setGravity(Gravity.CENTER);TextView icon=text(icons[i],20,destination.equals(names[i])?ACCENT:INK);icon.setGravity(Gravity.CENTER);if((i==0&&destination.equals("home"))||(i==1&&(destination.equals("records")||destination.equals("session")))||(i==2&&destination.equals("settings")))icon.setBackground(round(0xFFDBDCF4,18));item.addView(icon,new LinearLayout.LayoutParams(dp(48),dp(27)));TextView label=text(names[i],10,INK);label.setGravity(Gravity.CENTER);item.addView(label);item.setOnClickListener(v->{if(n==0)showHome();else if(n==1)showRecords();else showSettings();});nav.addView(item,new LinearLayout.LayoutParams(0,dp(58),1));}root.addView(nav);}
 private LinearLayout scrolling(LinearLayout into){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);LinearLayout c=column();c.setPadding(dp(12),dp(8),dp(12),dp(18));sc.addView(c);into.addView(sc,new LinearLayout.LayoutParams(-1,-1));return c;}
 private LinearLayout card(LinearLayout into,String name){LinearLayout c=column();c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(round(CARD,6));if(!name.isEmpty()){c.addView(text(name,13,ACCENT));View line=new View(this);line.setBackgroundColor(0xFFD3D0E1);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(1));lp.setMargins(0,dp(7),0,dp(7));c.addView(line,lp);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(8));into.addView(c,p);return c;}
 private void pair(LinearLayout into,String name,String value){LinearLayout r=row();r.setPadding(0,dp(3),0,dp(3));r.addView(text(name,12,MUTED),new LinearLayout.LayoutParams(0,-2,1));TextView v=text(value,12,INK);v.setGravity(Gravity.END);r.addView(v,new LinearLayout.LayoutParams(-2,-2));into.addView(r);}
 private void note(LinearLayout c,String s){TextView t=text(s,12,MUTED);t.setPadding(0,dp(6),0,dp(9));c.addView(t);}
 private EditText field(LinearLayout c,String name,String value,String hint){c.addView(text(name,12,ACCENT));EditText t=new EditText(this);t.setSingleLine(true);t.setTextSize(14);t.setTextColor(INK);t.setText(value);t.setHint(hint);c.addView(t,new LinearLayout.LayoutParams(-1,dp(44)));return t;}
 private Spinner choice(LinearLayout into,String label,String[] shown,String[] values,String current,String key){into.addView(text(label,12,ACCENT));Spinner s=new Spinner(this);ArrayAdapter<String> a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,shown);s.setAdapter(a);int n=0;for(int i=0;i<values.length;i++)if(values[i].equals(current))n=i;s.setSelection(n);into.addView(s,new LinearLayout.LayoutParams(-1,dp(42)));s.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> p,View v,int pos,long id){if(key.endsWith("Period")||key.equals("targetFps"))new Config(MainActivity.this).prefs.edit().putInt(key,Integer.parseInt(values[pos])).apply();else new Config(MainActivity.this).prefs.edit().putString(key,values[pos]).apply();}public void onNothingSelected(AdapterView<?> p){}});return s;}
 private void toggle(LinearLayout c,String label,String key,boolean value){Switch s=new Switch(this);s.setText(label);s.setTextSize(13);s.setTextColor(INK);s.setChecked(value);s.setPadding(0,dp(8),0,dp(8));s.setOnCheckedChangeListener((b,v)->new Config(this).prefs.edit().putBoolean(key,v).apply());c.addView(s);}
 private void showHome(){shell("轻帧", "home",false);LinearLayout c=scrolling(body);Config cfg=new Config(this);LinearLayout connect=card(c,"采集");statusView=text(MonitorService.status,14,INK);connect.addView(statusView);note(connect,"Root / Shizuku / Sui 自动适配 · 所有记录保存在本机");choice(connect,"授权方式",new String[]{"自动选择","Shizuku / Sui","Root","基础模式"},new String[]{"auto","shizuku","root","basic"},cfg.mode,"mode");buttons(connect,"Shizuku 授权",()->authorize(),"悬浮窗授权",()->startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName()))));EditText title=field(connect,"记录名称",cfg.title,"例如：使命召唤手游"),pkg=field(connect,"目标包名（可选）",cfg.packageName,"留空自动选择活动游戏图层");buttons(connect,"开始记录",()->{if(MonitorService.running){toast("正在记录，设置在下一次记录生效");return;}cfg.prefs.edit().putString("title",title.getText().toString().trim().isEmpty()?"性能记录":title.getText().toString().trim()).putString("package",pkg.getText().toString().trim()).apply();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},102);startForegroundService(new Intent(this,MonitorService.class).setAction("start"));},"停止并保存",()->serviceAction("stop"));buttons(connect,"暂停 / 继续",()->serviceAction("pause"),"悬浮窗显示 / 隐藏",()->serviceAction("hide"));if(MonitorService.running&&!MonitorService.sessionPath.isEmpty())connect.addView(button("查看当前记录快照",()->openSession(new File(MonitorService.sessionPath))));
  LinearLayout l=card(c,"实时数值");String[] keys={"fps","frameMs","cpuPct","gpuPct","gpuMHz","cpuC","gpuC","socC","batteryC","powerW","currentMA","ramUsedMB","rxKBs","txKBs","monitorCpuPct","monitorRssMB"};for(String k:keys){LinearLayout r=row();r.setPadding(0,dp(4),0,dp(4));r.addView(text(Config.label(k),12,MUTED),new LinearLayout.LayoutParams(0,-2,1));TextView value=text("—",14,INK);r.addView(value);live.put(k,value);l.addView(r);}note(c,"默认帧采样 250ms，硬件 1s，温度 2s。FPS 是近 1 秒的滚动值。读不到的指标显示 —；GPU 节点需要按机型验证。");shownLive="";
 }
 private void authorize(){try{if(Shizuku.pingBinder()){if(Shizuku.checkSelfPermission()==PackageManager.PERMISSION_GRANTED)toast("Shizuku 已授权");else Shizuku.requestPermission(101);}else{Intent i=getPackageManager().getLaunchIntentForPackage("moe.shizuku.privileged.api");if(i!=null)startActivity(i);else toast("请先安装并启动 Shizuku");}}catch(Exception e){toast(e.toString());}}
 private void serviceAction(String a){if(MonitorService.running)startService(new Intent(this,MonitorService.class).setAction(a));else toast("尚未开始记录");}
 private void showSettings(){shell("设置", "settings",false);LinearLayout c=scrolling(body);Config f=new Config(this);LinearLayout rates=card(c,"采样与悬浮窗");note(rates,"更改在下一次记录生效。降低采样频率可减少开销。");choice(rates,"帧采样间隔",new String[]{"100 ms","250 ms（默认）","500 ms","1000 ms"},new String[]{"100","250","500","1000"},""+f.framePeriod,"framePeriod");choice(rates,"硬件间隔",new String[]{"500 ms","1000 ms","2000 ms"},new String[]{"500","1000","2000"},""+f.hardwarePeriod,"hardwarePeriod");choice(rates,"温度间隔",new String[]{"1000 ms","2000 ms","5000 ms"},new String[]{"1000","2000","5000"},""+f.tempPeriod,"tempPeriod");choice(rates,"目标帧率（用于长帧估算）",new String[]{"30","60","90","120","144","165"},new String[]{"30","60","90","120","144","165"},""+f.targetFps,"targetFps");toggle(rates,"记录帧率和逐帧时间", "frames",f.frames);toggle(rates,"启用悬浮窗", "overlay",f.overlay);rates.addView(button("选择悬浮窗指标",()->overlaySelection()));note(rates,"拖动悬浮窗移动；双击打开轻帧；长按隐藏。通知可继续显示或停止保存。");
  LinearLayout adapter=card(c,"GPU 适配与图层");EditText freq=field(adapter,"GPU 频率节点",f.gpuFreqPath,"/sys/… 或 /proc/…，空白自动探测");choice(adapter,"频率节点单位",new String[]{"Hz","kHz","MHz"},new String[]{"Hz","kHz","MHz"},f.gpuFreqUnit,"gpuFreqUnit");EditText load=field(adapter,"GPU 使用率节点",f.gpuLoadPath,"空白自动探测");choice(adapter,"GPU 使用率格式",new String[]{"百分比 / 首个数值","busy total 两个计数"},new String[]{"percent","busy_total"},f.gpuLoadFormat,"gpuLoadFormat");EditText temp=field(adapter,"GPU 温度节点",f.gpuTempPath,"空白自动探测"),layer=field(adapter,"固定 SurfaceFlinger 图层",f.layer,"空白自动选择");adapter.addView(button("保存适配设置",()->{String[] p={freq.getText().toString().trim(),load.getText().toString().trim(),temp.getText().toString().trim()};for(String v:p)if(!v.isEmpty()&&!Numbers.safeNode(v)){toast("节点必须位于 /sys 或 /proc，且不能包含 ..");return;}f.prefs.edit().putString("gpuFreqPath",p[0]).putString("gpuLoadPath",p[1]).putString("gpuTempPath",p[2]).putString("layer",layer.getText().toString().trim()).apply();toast("已保存，下次记录生效");}));gap(adapter,8);adapter.addView(button("查看可用图层",()->listLayers(layer)));
  LinearLayout d=card(c,"诊断与数据");d.addView(button("导出采集诊断",()->diagnose()));note(d,"诊断包括设备信息、节点权限、原始节点值和图层，用于适配 vivo / 联发科等设备。记录不设期限；支持完整 CSV、ZIP 和曲线图片导出。");pair(d,"版本","0.2.0 · 测试版");note(d,"免费、无联网权限。原生界面，不使用 WebView。CPU/RAM 为系统指标；功率为电池侧估算。温度和 GPU 节点的可用性取决于系统权限。尚未在你的手机和平板上测量实际开销。");
 }
 private void overlaySelection(){String saved=new Config(this).prefs.getString("overlayKeys","fps,frameMs,cpuPct,gpuPct,gpuMHz,cpuC,gpuC,powerW");Set<String> selected=new LinkedHashSet<>(Arrays.asList(saved.split(",")));boolean[] checked=new boolean[Config.METRICS.length];for(int i=0;i<checked.length;i++)checked[i]=selected.contains(Config.METRICS[i]);new AlertDialog.Builder(this).setTitle("悬浮窗指标（最多 12 项）").setMultiChoiceItems(Config.LABELS,checked,(d,n,v)->checked[n]=v).setPositiveButton("保存",(d,n)->{ArrayList<String>a=new ArrayList<>();for(int i=0;i<checked.length;i++)if(checked[i])a.add(Config.METRICS[i]);if(a.isEmpty()||a.size()>12){toast("请选择 1 至 12 项");return;}new Config(this).prefs.edit().putString("overlayKeys",String.join(",",a)).apply();toast("已保存，下次记录生效");}).setNegativeButton("取消",null).show();}
 private void listLayers(EditText target){toast("正在读取图层…");java.util.function.Consumer<String> show=json->{try{JSONArray arr=new JSONObject(json).getJSONArray("layers");String[] names=new String[arr.length()];for(int i=0;i<names.length;i++)names[i]=arr.getString(i);if(!destroyed)new AlertDialog.Builder(this).setTitle("选择图层").setItems(names,(d,n)->target.setText(names[n])).setNegativeButton("取消",null).show();}catch(Exception e){toast(json);}};if(MonitorService.running&&MonitorService.instance!=null){MonitorService.instance.layers(show);return;}String mode=new Config(this).mode;io.execute(()->{try(Backend b=Backend.connect(this,mode)){JSONObject req=new JSONObject();req.put("op","layers");String result=b.request(req).toString();ui.post(()->show.accept(result));}catch(Exception e){ui.post(()->toast(e.toString()));}});}

 private void diagnose(){toast("正在采集诊断…");java.util.function.Consumer<String> save=s->{io.execute(()->{try{File root=new File(getCacheDir(),"exports");root.mkdirs();File f=new File(root,"LightFrame-diagnostics.txt");try(Writer w=new OutputStreamWriter(new FileOutputStream(f),StandardCharsets.UTF_8)){w.write(Build.MANUFACTURER+" "+Build.MODEL+" Android "+Build.VERSION.RELEASE+"\n"+s);}ui.post(()->exportFile(f));}catch(Exception e){ui.post(()->toast(e.toString()));}});};if(MonitorService.running&&MonitorService.instance!=null)MonitorService.instance.diagnose(save);else io.execute(()->{try(Backend b=Backend.connect(this,new Config(this).mode)){JSONObject req=new JSONObject();req.put("op","diagnose");req.put("frames",false);req.put("config",new Config(this).json());save.accept(b.request(req).toString(2));}catch(Exception e){save.accept(e.toString());}});}
 private void showRecords(){shell("记录", "records",false);LinearLayout c=scrolling(body);File root=new File(getFilesDir(),"sessions");File[] files=root.listFiles(File::isDirectory);if(files==null||files.length==0){note(c,"还没有记录。开始监测后，停止时会自动保存。");return;}Arrays.sort(files,(a,b)->b.getName().compareTo(a.getName()));for(File f:files){JSONObject j=readSummary(f);LinearLayout card=card(c,j.optString("title",f.getName()));pair(card,"时间",new java.text.SimpleDateFormat("MM-dd HH:mm:ss",Locale.getDefault()).format(new Date(j.optLong("startedUnixMs",f.lastModified()))));pair(card,"时长 / 采样",Config.elapsed(j.optDouble("durationSeconds",0))+" / "+j.optInt("samples",0));pair(card,"设备 / 采集器",j.optString("device","")+" · "+j.optString("backend",""));String status=j.optString("status","partial");if(!status.equals("complete"))note(card,status.equals("recording")?"进行中或未正常结束；已有数据仍可查看":"不完整记录；已有数据仍可查看");card.setOnClickListener(v->openSession(f));card.setContentDescription("打开记录 "+j.optString("title",f.getName()));}}
 private JSONObject readSummary(File dir){try{return new JSONObject(new String(java.nio.file.Files.readAllBytes(new File(dir,"summary.json").toPath()),StandardCharsets.UTF_8));}catch(Exception e){return new JSONObject();}}
 private void closeIndexes(){try{if(sampleIndex!=null)sampleIndex.close();}catch(Exception ignored){}try{if(frameIndex!=null)frameIndex.close();}catch(Exception ignored){}sampleIndex=frameIndex=null;}
 private void openSession(File f){session=f;selectedRow=selectedFrame=-1;samplePage=framePage=0;tab=0;summary=readSummary(f);shell(summary.optString("title",f.getName()),"session",true);TextView share=text("↗",24,INK);share.setGravity(Gravity.CENTER);share.setContentDescription("导出记录");share.setOnClickListener(v->exportMenu());header.addView(share,new LinearLayout.LayoutParams(dp(40),dp(50)));TextView del=text("⋮",24,INK);del.setGravity(Gravity.CENTER);del.setContentDescription("记录操作");del.setOnClickListener(v->sessionMenu());header.addView(del,new LinearLayout.LayoutParams(dp(32),dp(50)));HorizontalScrollView horizontal=new HorizontalScrollView(this);horizontal.setHorizontalScrollBarEnabled(false);LinearLayout tabs=row();historyTabs=tabs;for(int i=0;i<Config.TABS.length;i++){final int n=i;LinearLayout cell=column();TextView t=text(Config.TABS[i],12,ACCENT);t.setGravity(Gravity.CENTER);cell.addView(t,new LinearLayout.LayoutParams(dp(i>8?86:60),dp(36)));View line=new View(this);line.setBackgroundColor(i==0?ACCENT:0xFFDCD7E8);cell.addView(line,new LinearLayout.LayoutParams(-1,dp(2)));cell.setOnClickListener(v->{for(int x=0;x<tabs.getChildCount();x++)((LinearLayout)tabs.getChildAt(x)).getChildAt(1).setBackgroundColor(x==n?ACCENT:0xFFDCD7E8);tab=n;renderTab();});tabs.addView(cell);}horizontal.addView(tabs);body.addView(horizontal);historyBody=column();body.addView(historyBody,new LinearLayout.LayoutParams(-1,0,1));content=scrolling(historyBody);note(content,"正在建立原始数据索引…");int token=++generation;io.execute(()->{try{closeIndexes();sampleIndex=new CsvIndex(new File(f,"samples.csv"));File frames=new File(f,"frames.csv");if(frames.isFile())frameIndex=new CsvIndex(frames);ui.post(()->{if(!destroyed&&token==generation)renderTab();});}catch(Exception e){ui.post(()->{if(!destroyed&&token==generation){content.removeAllViews();note(content,"读取失败："+e);}});}});}
 private void renderTab(){if(sampleIndex==null||historyBody==null)return;if(historyTabs!=null)for(int i=0;i<historyTabs.getChildCount();i++)((LinearLayout)historyTabs.getChildAt(i)).getChildAt(1).setBackgroundColor(i==tab?ACCENT:0xFFDCD7E8);int token=++generation;charts.clear();historyBody.removeAllViews();content=scrolling(historyBody);if(tab==0){overview();return;}if(tab==9||tab==10){renderRows(tab==10,token);return;}String[] keys=Config.GROUPS[tab];note(content,"点曲线查看原始采样 · 双指缩放 · 左右拖动 · 双击复位");LinearLayout holder=column();content.addView(holder);detail=card(content,"本次采样 · 全部指标");note(detail,"点选任意曲线，查看该时刻全部数值；可逐条前进或后退。");final CsvIndex source=sampleIndex;io.execute(()->{try{ChartData[] a=ChartData.load(source,keys);ui.post(()->{if(destroyed||token!=generation)return;for(ChartData d:a){if(d.count==0&&tab==3)continue;HistoryChart chart=new HistoryChart(this,d);chart.onSelect=t->selectTime(t);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(190));p.setMargins(0,0,0,dp(8));holder.addView(chart,p);charts.add(chart);}if(holder.getChildCount()==0)note(holder,"未取得此组指标");if(selectedRow>=0)showSample(selectedRow);});}catch(Exception e){ui.post(()->{if(token==generation)note(holder,"读取失败: "+e);});}});}
 private void overview(){LinearLayout fps=card(content,"FPS");JSONObject st=summary.optJSONObject("statistics"),f=st==null?null:st.optJSONObject("fps");pair(fps,"平均 / 最低 / 最高",f==null?"—":Numbers.display(f.optDouble("avg"),1)+" / "+Numbers.display(f.optDouble("min"),1)+" / "+Numbers.display(f.optDouble("max"),1));pair(fps,"P1 / P5（FPS 采样值）",f==null?"—":Numbers.display(f.optDouble("p1"),1)+" / "+Numbers.display(f.optDouble("p5"),1));pair(fps,"FPS 波动（标准差）",f==null?"—":Numbers.display(f.optDouble("stdDev"),2));pair(fps,"1% Low / 0.1% Low",Numbers.display(summary.optDouble("low1Pct"),1)+" / "+Numbers.display(summary.optDouble("low01Pct"),1));pair(fps,"捕获帧区间数",""+summary.optLong("capturedIntervals"));pair(fps,"捕获帧平均 FPS",Numbers.display(summary.optDouble("capturedFrameAverageFps"),1));LinearLayout other=card(content,"硬件均值");for(String k:new String[]{"cpuPct","gpuPct","gpuMHz","ramUsedMB","powerW","cpuC","gpuC","socC","batteryC","monitorCpuPct","monitorRssMB"}){JSONObject s=st==null?null:st.optJSONObject(k);pair(other,Config.label(k),Config.format(k,s==null?Double.NaN:s.optDouble("avg")));}LinearLayout longframes=card(content,"长帧估算");pair(longframes,"长帧 / 严重长帧",summary.optLong("longFramesEstimate")+" / "+summary.optLong("bigLongFramesEstimate"));note(longframes,"按目标帧预算的 1.5 倍 / 3 倍估算，不等同于官方 Jank 或商业工具口径。");LinearLayout data=card(content,"记录信息");pair(data,"原始采样数",""+sampleIndex.count);pair(data,"时长",Config.elapsed(summary.optDouble("durationSeconds",0)));pair(data,"采集方式",summary.optString("backend","")+" · UID "+summary.optInt("uid"));pair(data,"设备",summary.optString("device",""));note(data,"空值表示未取得。硬件 / 温度各自更新，采样明细会显示数据距今。曲线在长记录中按最小和最大值合并绘制，原始值全部保留。");data.addView(button("从第一条开始查看",()->{tab=9;renderTab();}));}
 private void selectTime(double t){final CsvIndex source=sampleIndex;int token=generation;io.execute(()->{try{int row=source.nearest(t);ui.post(()->{if(token==generation&&row>=0)showSample(row);});}catch(Exception e){ui.post(()->toast(e.toString()));}});}
 private void showSample(int n){if(sampleIndex==null||sampleIndex.count==0)return;int index=Math.max(0,Math.min(sampleIndex.count-1,n));final CsvIndex source=sampleIndex;int token=generation;io.execute(()->{try{String[] r=source.row(index);ui.post(()->{if(destroyed||token!=generation)return;selectedRow=index;double time=CsvIndex.time(r);for(HistoryChart chart:charts)chart.select(time,source.value(r,chart.data.key));if(detail!=null){detail.removeAllViews();sampleDetails(detail,source,r,index);} });}catch(Exception e){ui.post(()->toast(e.toString()));}});}
 private void sampleDetails(LinearLayout box,CsvIndex source,String[] r,int n){TextView heading=text("第 "+(n+1)+" / "+source.count+" 次采样 · "+Config.elapsed(CsvIndex.time(r)),14,ACCENT);box.addView(heading);gap(box,8);buttons(box,"‹ 上一条",()->showSample(n-1),"下一条 ›",()->showSample(n+1));box.addView(button("查看原始数值",()->rawValues(source,r)));gap(box,6);for(String k:Config.METRICS)pair(box,Config.label(k),Config.format(k,source.value(r,k)));for(int i=0;i<16;i++){String k="cpu"+i+"MHz";double v=source.value(r,k);if(Double.isFinite(v))pair(box,Config.label(k),Config.format(k,v));}for(String k:new String[]{"paused","charging","thermalStatus","frameStatus","gpuLoadStatus","gpuFrequencyStatus","gpuTemperatureStatus","layer","longFramesEstimate","bigLongFramesEstimate","unix_ms"}){int i=source.column(k);if(i>=0&&i<r.length&&!r[i].isEmpty())note(box,statusLabel(k)+"："+r[i]);}}
 private void rawValues(CsvIndex source,String[] r){StringBuilder s=new StringBuilder();for(int i=0;i<source.header.length;i++){String k=source.header[i];s.append(Config.label(k)).append(" [").append(k).append("]\n").append(i<r.length&&!r[i].isEmpty()?r[i]:"未取得").append(" ").append(Config.unit(k)).append("\n\n");}TextView t=text(s.toString(),13,INK);t.setTextIsSelectable(true);t.setPadding(dp(18),dp(12),dp(18),dp(12));ScrollView sc=new ScrollView(this);sc.addView(t);new AlertDialog.Builder(this).setTitle("原始采样值（可复制）").setView(sc).setPositiveButton("关闭",null).show();}
 private String statusLabel(String s){switch(s){case "paused":return "暂停标记";case "charging":return "充电中";case "thermalStatus":return "系统热状态";case "frameStatus":return "帧来源 / 状态";case "gpuLoadStatus":return "GPU 使用率来源";case "gpuFrequencyStatus":return "GPU 频率来源";case "gpuTemperatureStatus":return "GPU 温度来源";case "layer":return "图层";case "longFramesEstimate":return "累计长帧估算";case "bigLongFramesEstimate":return "累计严重长帧估算";case "unix_ms":return "时间戳（ms）";default:return s;}}
 private void renderRows(boolean frames,int token){CsvIndex source=frames?frameIndex:sampleIndex;if(source==null||source.count==0){note(content,"暂无"+(frames?"逐帧":"采样")+"数据");return;}int pageNum=frames?framePage:samplePage;int from=Math.min(source.count-1,pageNum*50),end=Math.min(source.count,from+50);LinearLayout controls=card(content,frames?"逐帧时间（原始记录）":"采样明细（原始记录）");pair(controls,"范围",(from+1)+"—"+end+" / "+source.count);buttons(controls,"‹ 上一页",()->{if(frames)framePage=Math.max(0,framePage-1);else samplePage=Math.max(0,samplePage-1);renderTab();},"下一页 ›",()->{if(frames)framePage=Math.min((source.count-1)/50,framePage+1);else samplePage=Math.min((source.count-1)/50,samplePage+1);renderTab();});LinearLayout jump=row();EditText number=new EditText(this);number.setHint("跳到序号");number.setTextSize(13);number.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);jump.addView(number,new LinearLayout.LayoutParams(0,dp(42),1));jump.addView(button("跳转",()->{try{int n=Math.max(0,Math.min(source.count-1,Integer.parseInt(number.getText().toString())-1));if(frames){framePage=n/50;selectedFrame=n;}else{samplePage=n/50;selectedRow=n;}renderTab();}catch(Exception e){toast("请输入采样序号");}}));controls.addView(jump);note(controls,frames?"间隔来自实际呈现时间。未被 SurfaceFlinger 缓冲返回的帧无法补回。点击可逐帧查看。":"每一行都来自原始 CSV。点行查看全部指标，上一条 / 下一条按原始顺序移动。");
  LinearLayout list=card(content,frames?"序号 · 时间 · 间隔":"序号 · 时间 · FPS · CPU · GPU");detail=card(content,frames?"本帧详情":"本次采样 · 全部指标");io.execute(()->{try{ArrayList<String[]> rows=new ArrayList<>();for(int n=from;n<end;n++)rows.add(source.row(n));ui.post(()->{if(destroyed||token!=generation)return;for(int x=0;x<rows.size();x++){int n=from+x;String[] r=rows.get(x);String label=String.format(Locale.US,"#%d   %s   ",n+1,Config.elapsed(CsvIndex.time(r)));if(frames)label+=Numbers.display(source.value(r,"interval_ms"),3)+" ms";else label+=Numbers.display(source.value(r,"fps"),1)+"    "+Numbers.display(source.value(r,"cpuPct"),1)+"%    "+Numbers.display(source.value(r,"gpuPct"),1)+"%";TextView t=text(label,12,INK);t.setPadding(0,dp(10),0,dp(10));t.setBackground(round(n==(frames?selectedFrame:selectedRow)?0xFFD6D5EC:CARD,3));t.setOnClickListener(v->{if(frames)showFrame(n);else showSample(n);((ScrollView)content.getParent()).smoothScrollTo(0,detail.getTop());});list.addView(t);View line=new View(this);line.setBackgroundColor(0xFFD3D0E1);list.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));}if(frames)showFrame(selectedFrame>=from&&selectedFrame<end?selectedFrame:from);else showSample(selectedRow>=from&&selectedRow<end?selectedRow:from);});}catch(Exception e){ui.post(()->toast(e.toString()));}});
 }
 private void showFrame(int n){final CsvIndex source=frameIndex;if(source==null||source.count==0)return;int index=Math.max(0,Math.min(source.count-1,n)),token=generation;io.execute(()->{try{String[] r=source.row(index);ui.post(()->{if(token!=generation||destroyed)return;selectedFrame=index;detail.removeAllViews();detail.addView(text("第 "+(index+1)+" / "+source.count+" 帧 · "+Config.elapsed(CsvIndex.time(r)),14,ACCENT));gap(detail,8);buttons(detail,"‹ 上一帧",()->showFrame(index-1),"下一帧 ›",()->showFrame(index+1));pair(detail,"帧间隔",Numbers.display(source.value(r,"interval_ms"),6)+" ms");pair(detail,"瞬时帧率（间隔倒数）",Numbers.display(1000/source.value(r,"interval_ms"),2)+" fps");for(int i=0;i<source.header.length&&i<r.length;i++)if(!source.header[i].equals("interval_ms"))note(detail,source.header[i]+"："+r[i]);});}catch(Exception e){ui.post(()->toast(e.toString()));}});}
 private void sessionMenu(){new AlertDialog.Builder(this).setItems(new String[]{"刷新当前记录快照","删除记录"},(d,n)->{if(n==0)openSession(session);else{if(MonitorService.running&&session.getAbsolutePath().equals(MonitorService.sessionPath)){toast("请先停止正在记录的会话");return;}new AlertDialog.Builder(this).setTitle("删除此记录？").setMessage("这会删除该记录的全部原始数据。").setNegativeButton("取消",null).setPositiveButton("删除",(dialog,which)->{File f=session;generation++;io.execute(()->{closeIndexes();boolean ok=deleteTree(f);ui.post(()->{toast(ok?"已删除":"删除失败");showRecords();});});}).show();}}).show();}
 private boolean deleteTree(File f){File[] a=f.listFiles();if(a!=null)for(File child:a)if(!deleteTree(child))return false;return f.delete();}
 private void exportMenu(){if(session==null)return;new AlertDialog.Builder(this).setTitle("导出").setItems(new String[]{"全部数据 ZIP","采样数值 CSV","逐帧数值 CSV","当前曲线 PNG"},(d,n)->{if(n==1)exportFile(new File(session,"samples.csv"));else if(n==2)exportFile(new File(session,"frames.csv"));else if(n==3){if(charts.isEmpty()){toast("先打开一个指标曲线");return;}String[] labels=new String[charts.size()];for(int i=0;i<labels.length;i++)labels[i]=Config.label(charts.get(i).data.key);new AlertDialog.Builder(this).setTitle("选择曲线").setItems(labels,(dialog,x)->makeImage(charts.get(x))).show();}else makeZip();}).show();}
 private void makeZip(){File src=session;toast("正在打包完整记录…");io.execute(()->{try{File dest=new File(getCacheDir(),"exports");dest.mkdirs();File zip=new File(dest,src.getName()+".zip");try(ZipOutputStream out=new ZipOutputStream(new BufferedOutputStream(new FileOutputStream(zip)))){File[] files=src.listFiles(File::isFile);if(files!=null)for(File f:files)if(!f.getName().endsWith(".tmp")){out.putNextEntry(new ZipEntry(f.getName()));try(InputStream in=new FileInputStream(f)){byte[] b=new byte[32768];for(int n;(n=in.read(b))!=-1;)out.write(b,0,n);}out.closeEntry();}}ui.post(()->exportFile(zip));}catch(Exception e){ui.post(()->toast(e.toString()));}});}
 private void makeImage(HistoryChart chart){File dest=new File(getCacheDir(),"exports");dest.mkdirs();File out=new File(dest,session.getName()+"_"+chart.data.key+".png");Bitmap image=Bitmap.createBitmap(1000,680,Bitmap.Config.ARGB_8888);try{Canvas c=new Canvas(image);c.drawColor(BG);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(INK);p.setTextSize(30);c.drawText(summary.optString("title","轻帧记录"),24,46,p);p.setTextSize(18);p.setColor(MUTED);c.drawText(summary.optString("device","")+" · "+summary.optString("backend","")+" · "+sampleIndex.count+" 次采样",24,78,p);c.save();c.translate(24,105);chart.render(c,952,470);c.restore();p.setTextSize(18);c.drawText("轻帧 0.2.0 · 曲线仅合并绘制；全部原始数值保存在 CSV",24,615,p);c.drawText("空值表示未取得；功率为电池侧估算；指标按各自间隔采集",24,644,p);try(OutputStream s=new FileOutputStream(out)){image.compress(Bitmap.CompressFormat.PNG,100,s);}exportFile(out);}catch(Exception e){toast(e.toString());}finally{image.recycle();}}
 private String mime(File f){return f.getName().endsWith(".csv")?"text/csv":f.getName().endsWith(".png")?"image/png":f.getName().endsWith(".txt")?"text/plain":"application/zip";}
 private void exportFile(File f){if(!f.isFile()){toast("文件尚未生成");return;}new AlertDialog.Builder(this).setTitle(f.getName()).setItems(new String[]{"保存到文件","分享"},(d,n)->{try{if(n==0){pendingExport=f;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime(f));i.putExtra(Intent.EXTRA_TITLE,f.getName());startActivityForResult(i,201);}else{Uri uri=ExportProvider.uri(this,f);Intent i=new Intent(Intent.ACTION_SEND);i.setType(mime(f));i.putExtra(Intent.EXTRA_STREAM,uri);i.setClipData(ClipData.newRawUri(f.getName(),uri));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"分享记录"));}}catch(Exception e){toast(e.toString());}}).show();}
 @Override protected void onActivityResult(int code,int result,Intent data){super.onActivityResult(code,result,data);if(code==201&&result==RESULT_OK&&data!=null&&data.getData()!=null&&pendingExport!=null){Uri uri=data.getData();File src=pendingExport;pendingExport=null;io.execute(()->{try(InputStream in=new FileInputStream(src);OutputStream out=getContentResolver().openOutputStream(uri)){if(out==null)throw new IOException("无法打开目标文件");byte[] b=new byte[32768];for(int n;(n=in.read(b))!=-1;)out.write(b,0,n);ui.post(()->toast("已保存"));}catch(Exception e){ui.post(()->toast("保存失败："+e));}});}}
 @Override public void onBackPressed(){if(page.equals("session"))showRecords();else if(!page.equals("home"))showHome();else super.onBackPressed();}
 private void toast(String s){if(!destroyed)Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
