package com.lightframe.monitor;

import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;import java.util.zip.*;import rikka.shizuku.Shizuku;

/** Native Views and Canvas, styled from the user's RakkaRecorder recording. */
public final class MainActivity extends Activity{
 private static final int BG=0xFFF8F5FF,CARD=0xFFE2DFED,INK=0xFF3F3A49,MUTED=0xFF706B82,ACCENT=0xFF656D9E;
 private final Handler ui=new Handler(Looper.getMainLooper());private final ExecutorService io=Executors.newSingleThreadExecutor();
 private LinearLayout root,body,header,nav,content,detail,historyBody,historyTabs;private TextView statusView,captureStatus;private final Map<String,TextView> live=new LinkedHashMap<>();private String shownLive="",page="home";private File session,pendingExport;private CsvIndex sampleIndex,frameIndex;private JSONObject summary;private int tab,generation,selectedRow=-1,selectedFrame=-1,samplePage,framePage;private final ArrayList<HistoryChart> charts=new ArrayList<>();private boolean destroyed;private int sessionGeneration,dataGeneration;private final HistorySelection selection=new HistorySelection();private final ExecutorService historyIo=Executors.newSingleThreadExecutor(),selectionIo=Executors.newSingleThreadExecutor();private Future<?> historyJob;private HistoryViewport viewport;private HistoryRange rangeStats;private LinearLayout chartHolder;private TextView rangeLabel,historyState;private double restoredBegin=Double.NaN,restoredEnd=Double.NaN;private String[] selectedSample;private int rangeFrom,rangeTo;
 private final Runnable refresh=new Runnable(){public void run(){if(page.equals("home")){if(statusView!=null)statusView.setText(MonitorService.status);String s=MonitorService.latest;if(!shownLive.equals(s)){shownLive=s;try{JSONObject j=new JSONObject(s);for(Map.Entry<String,TextView> e:live.entrySet())e.getValue().setText(Config.formatSample(e.getKey(),j));if(captureStatus!=null)captureStatus.setText(captureStatus(j));}catch(Exception ignored){}}}ui.postDelayed(this,250);}};
 private boolean resumed,guidedAuthPending;private TextView accessSummary,guideSummary;
 private final Shizuku.OnBinderReceivedListener accessReceived=()->ui.post(()->{refreshAccessStatus();finishGuidedAuthorization();});
 private final Shizuku.OnBinderDeadListener accessDead=()->ui.post(this::refreshAccessStatus);
 private final Shizuku.OnRequestPermissionResultListener permission=(code,result)->{if(code==101){guidedAuthPending=false;refreshAccessStatus();toast(result==PackageManager.PERMISSION_GRANTED?"Shizuku 已授权":"未获得 Shizuku 授权");}};
 @Override public void onCreate(Bundle saved){super.onCreate(saved);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(0xFFEEEBF6);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(BG);root.addOnLayoutChangeListener((v,left,top,right,bottom,oldLeft,oldTop,oldRight,oldBottom)->{if(right-left!=oldRight-oldLeft||bottom-top!=oldBottom-oldTop)updateChartHeights();});root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});setContentView(root);Shizuku.addRequestPermissionResultListener(permission);Shizuku.addBinderReceivedListenerSticky(accessReceived);Shizuku.addBinderDeadListener(accessDead);if(saved!=null&&saved.getString("export")!=null)pendingExport=new File(saved.getString("export"));if(saved!=null&&saved.getString("session")!=null&&new File(saved.getString("session")).isDirectory()){openSession(new File(saved.getString("session")));tab=saved.getInt("tab",0);selectedRow=saved.getInt("row",-1);selectedFrame=saved.getInt("frame",-1);restoredBegin=saved.getDouble("begin",Double.NaN);restoredEnd=saved.getDouble("end",Double.NaN);}else showHome();}
 @Override protected void onResume(){super.onResume();resumed=true;refreshAccessStatus();finishGuidedAuthorization();ui.removeCallbacks(refresh);ui.post(refresh);}
 @Override protected void onPause(){resumed=false;ui.removeCallbacks(refresh);super.onPause();}
 @Override protected void onDestroy(){destroyed=true;generation++;sessionGeneration++;selection.request();if(historyJob!=null)historyJob.cancel(true);historyIo.shutdownNow();selectionIo.shutdownNow();ui.removeCallbacksAndMessages(null);Shizuku.removeRequestPermissionResultListener(permission);Shizuku.removeBinderReceivedListener(accessReceived);Shizuku.removeBinderDeadListener(accessDead);io.execute(()->closeIndexes());io.shutdown();super.onDestroy();}
 @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);if(pendingExport!=null)out.putString("export",pendingExport.getAbsolutePath());if(page.equals("session")&&session!=null){out.putString("session",session.getAbsolutePath());out.putInt("tab",tab);out.putInt("row",selectedRow);out.putInt("frame",selectedFrame);if(viewport!=null){out.putDouble("begin",viewport.begin);out.putDouble("end",viewport.end);}}}
 private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 private TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);return t;}
 private GradientDrawable round(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 private void gap(LinearLayout l,int h){l.addView(new View(this),new LinearLayout.LayoutParams(1,dp(h)));}
 private TextView button(String s,Runnable run){TextView t=text(s,13,ACCENT);t.setGravity(Gravity.CENTER);t.setPadding(dp(12),dp(10),dp(12),dp(10));t.setBackground(round(0xFFDCDCF1,18));t.setOnClickListener(v->run.run());t.setMinHeight(dp(40));return t;}
 private void buttons(LinearLayout parent,String a,Runnable ra,String b,Runnable rb){LinearLayout r=row();TextView x=button(a,ra),y=button(b,rb);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(42),1);p.setMargins(0,0,dp(8),0);r.addView(x,p);r.addView(y,new LinearLayout.LayoutParams(0,dp(42),1));parent.addView(r);gap(parent,8);}
 private void shell(String title,String destination,boolean back){page=destination;generation++;sessionGeneration++;selection.request();dataGeneration++;if(historyJob!=null)historyJob.cancel(true);detail=null;historyBody=null;historyTabs=null;chartHolder=null;rangeLabel=null;historyState=null;root.removeAllViews();live.clear();charts.clear();captureStatus=null;header=row();header.setPadding(dp(12),0,dp(12),0);TextView h=text(back?"‹":"◈",26,INK);h.setGravity(Gravity.CENTER);h.setContentDescription(back?"返回记录列表":"轻帧");h.setOnClickListener(v->{if(back)showRecords();});header.addView(h,new LinearLayout.LayoutParams(dp(36),dp(50)));header.addView(text(title,17,INK),new LinearLayout.LayoutParams(0,dp(54),1));root.addView(header);body=column();root.addView(body,new LinearLayout.LayoutParams(-1,0,1));nav=row();nav.setBackgroundColor(0xFFEEEBF6);String[] names={"主页","记录","设置"},icons={"⌂","▥","⚙"};for(int i=0;i<3;i++){final int n=i;LinearLayout item=column();item.setGravity(Gravity.CENTER);TextView icon=text(icons[i],20,destination.equals(names[i])?ACCENT:INK);icon.setGravity(Gravity.CENTER);if((i==0&&destination.equals("home"))||(i==1&&(destination.equals("records")||destination.equals("session")))||(i==2&&destination.equals("settings")))icon.setBackground(round(0xFFDBDCF4,18));item.addView(icon,new LinearLayout.LayoutParams(dp(48),dp(27)));TextView label=text(names[i],10,INK);label.setGravity(Gravity.CENTER);item.addView(label);item.setOnClickListener(v->{if(n==0)showHome();else if(n==1)showRecords();else showSettings();});nav.addView(item,new LinearLayout.LayoutParams(0,dp(58),1));}root.addView(nav);}
 private LinearLayout scrolling(LinearLayout into){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);LinearLayout c=column();c.setPadding(dp(12),dp(8),dp(12),dp(18));sc.addView(c);into.addView(sc,new LinearLayout.LayoutParams(-1,-1));return c;}
 private LinearLayout card(LinearLayout into,String name){LinearLayout c=column();c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackground(round(CARD,6));if(!name.isEmpty()){c.addView(text(name,13,ACCENT));View line=new View(this);line.setBackgroundColor(0xFFD3D0E1);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(1));lp.setMargins(0,dp(7),0,dp(7));c.addView(line,lp);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(8));into.addView(c,p);return c;}
 private void pair(LinearLayout into,String name,String value){LinearLayout r=row();r.setPadding(0,dp(3),0,dp(3));r.addView(text(name,12,MUTED),new LinearLayout.LayoutParams(0,-2,1));TextView v=text(value,12,INK);v.setGravity(Gravity.END);r.addView(v,new LinearLayout.LayoutParams(-2,-2));into.addView(r);}
 private void note(LinearLayout c,String s){TextView t=text(s,12,MUTED);t.setPadding(0,dp(6),0,dp(9));c.addView(t);}
 private EditText field(LinearLayout c,String name,String value,String hint){c.addView(text(name,12,ACCENT));EditText t=new EditText(this);t.setSingleLine(true);t.setTextSize(14);t.setTextColor(INK);t.setText(value);t.setHint(hint);c.addView(t,new LinearLayout.LayoutParams(-1,dp(44)));return t;}
 private Spinner choice(LinearLayout into,String label,String[] shown,String[] values,String current,String key){into.addView(text(label,12,ACCENT));Spinner s=new Spinner(this);ArrayAdapter<String> a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,shown);s.setAdapter(a);int n=0;for(int i=0;i<values.length;i++)if(values[i].equals(current))n=i;s.setSelection(n);into.addView(s,new LinearLayout.LayoutParams(-1,dp(42)));s.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> p,View v,int pos,long id){if(key.endsWith("Period")||key.equals("targetFps"))new Config(MainActivity.this).prefs.edit().putInt(key,Integer.parseInt(values[pos])).apply();else new Config(MainActivity.this).prefs.edit().putString(key,values[pos]).apply();}public void onNothingSelected(AdapterView<?> p){}});return s;}
 private void toggle(LinearLayout c,String label,String key,boolean value){Switch s=new Switch(this);s.setText(label);s.setTextSize(13);s.setTextColor(INK);s.setChecked(value);s.setPadding(0,dp(8),0,dp(8));s.setOnCheckedChangeListener((b,v)->new Config(this).prefs.edit().putBoolean(key,v).apply());c.addView(s);}
 private void showHome(){shell("轻帧", "home",false);LinearLayout c=scrolling(body);Config cfg=new Config(this);LinearLayout connect=card(c,"采集");statusView=text(MonitorService.status,14,INK);connect.addView(statusView);note(connect,"Root / Shizuku / Sui 自动适配 · 所有记录保存在本机");choice(connect,"授权方式",new String[]{"自动选择","Shizuku / Sui","Root","基础模式"},new String[]{"auto","shizuku","root","basic"},cfg.mode,"mode");buttons(connect,"Shizuku 授权",()->authorize(),"悬浮窗授权",()->startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName()))));accessSummary=text(accessStatus(),12,MUTED);connect.addView(accessSummary);connect.addView(button("采集授权向导",()->accessGuide()));EditText title=field(connect,"记录名称",cfg.title,"例如：使命召唤手游"),pkg=field(connect,"目标包名（可选）",cfg.packageName,"留空自动选择前台应用图层；指定包名可固定目标");buttons(connect,"开始记录",()->{if(MonitorService.running){toast(MonitorService.analyzing?"正在计算上一条记录，请稍候":"正在记录，设置在下一次记录生效");return;}cfg.prefs.edit().putString("title",title.getText().toString().trim().isEmpty()?"性能记录":title.getText().toString().trim()).putString("package",pkg.getText().toString().trim()).apply();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},102);startForegroundService(new Intent(this,MonitorService.class).setAction("start"));},"停止并保存",()->serviceAction("stop"));buttons(connect,"暂停 / 继续",()->serviceAction("pause"),"悬浮窗显示 / 隐藏",()->serviceAction("hide"));if(MonitorService.running&&!MonitorService.sessionPath.isEmpty())connect.addView(button("查看当前记录快照",()->openSession(new File(MonitorService.sessionPath))));
  LinearLayout state=card(c,"采集状态");captureStatus=text("开始记录后显示各项读取状态",12,MUTED);state.addView(captureStatus);LinearLayout l=card(c,"实时数值");String[] keys={"fps","frameMs","cpuPct","gpuPct","gpuMHz","cpuC","gpuC","socC","batteryC","powerW","currentMA","ramUsedMB","rxKBs","txKBs","monitorCpuPct","monitorRssMB"};for(String k:keys){LinearLayout r=row();r.setPadding(0,dp(4),0,dp(4));r.addView(text(Config.label(k),12,MUTED),new LinearLayout.LayoutParams(0,-2,1));TextView value=text("—",14,INK);r.addView(value);live.put(k,value);l.addView(r);}note(c,"默认帧采样 250ms，硬件 1s，温度 2s。FPS 是近 1 秒的滚动值。读不到的指标显示 —；GPU 节点需要按机型验证。");shownLive="";
 }
 private String captureStatus(JSONObject j){
  if(!j.has("frameStatus")&&!j.has("gpuFrequencyStatus"))return "开始记录后显示各项读取状态";
  StringBuilder b=new StringBuilder("FPS：").append(j.optString("frameStatus","未开启帧采集"));
  String[][] statuses={{"gpuPct","gpuLoadStatus","GPU 使用率"},{"gpuMHz","gpuFrequencyStatus","GPU 频率"},{"cpuC","cpuTemperatureStatus","CPU 温度"},{"gpuC","gpuTemperatureStatus","GPU 温度"},{"socC","socTemperatureStatus","SoC 温度"}};
  for(String[] row:statuses)if(!Double.isFinite(j.optDouble(row[0])))b.append("\n").append(row[2]).append("：").append(j.optString(row[1],"尚未取得数据"));
  return b.toString();
 }
 private void authorize(){try{if(Shizuku.pingBinder()){guidedAuthPending=false;if(Shizuku.checkSelfPermission()==PackageManager.PERMISSION_GRANTED){new Config(this).prefs.edit().putString("mode","shizuku").apply();toast("采集授权已就绪");}else Shizuku.requestPermission(101);}else{Intent i=getPackageManager().getLaunchIntentForPackage("moe.shizuku.privileged.api");if(i!=null){guidedAuthPending=true;startActivity(i);}else accessGuide();}refreshAccessStatus();}catch(Exception e){toast("授权未完成："+e.getMessage());}}
 private void finishGuidedAuthorization(){if(destroyed||!resumed||!guidedAuthPending||!Shizuku.pingBinder())return;guidedAuthPending=false;authorize();}
 private String accessStatus(){try{if(!Shizuku.pingBinder())return getPackageManager().getLaunchIntentForPackage("moe.shizuku.privileged.api")==null?"尚未检测到可用授权服务。无 Root 设备请先安装 Shizuku。":"Shizuku 已安装，采集服务未启动。请在 Shizuku 中启动后返回轻帧。";boolean granted=Shizuku.checkSelfPermission()==PackageManager.PERMISSION_GRANTED;int uid=Shizuku.getUid();return (granted?"轻帧已获授权":"轻帧尚未获得授权")+" · "+(uid==0?"Root 服务":uid==2000?"无线调试 / Shell 服务":"服务 UID "+uid)+(uid==2000?"\nGPU 能否读取仍取决于系统接口权限。":"");}catch(Exception e){return "授权状态暂不可确认，请重新检查。";}}
 private void refreshAccessStatus(){if(destroyed)return;String state=accessStatus();if(accessSummary!=null)accessSummary.setText(state);if(guideSummary!=null)guideSummary.setText(state);}
 private void externalPage(String url){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){toast("无法打开浏览器，请访问 "+url);}}
 private void accessGuide(){
  LinearLayout box=column();box.setPadding(dp(16),dp(12),dp(16),dp(12));guideSummary=text(accessStatus(),13,INK);box.addView(guideSummary);gap(box,10);
  note(box,"无 Root：安装 Shizuku → 开启无线调试并首次配对 → 在 Shizuku 启动 → 返回轻帧授权。返回后会自动重新检查；重启后需要再次启动服务。");
  box.addView(button("启动 / 授权 Shizuku",()->{try{if(!Shizuku.pingBinder()&&getPackageManager().getLaunchIntentForPackage("moe.shizuku.privileged.api")==null){externalPage("https://shizuku.rikka.app/download/");return;}authorize();}catch(Exception e){toast(e.getMessage());}}));gap(box,6);
  buttons(box,"打开开发者选项",()->{try{startActivity(new Intent(Settings.ACTION_APPLICATION_DEVELOPMENT_SETTINGS));}catch(Exception e){startActivity(new Intent(Settings.ACTION_SETTINGS));}},"重新检查授权",()->refreshAccessStatus());
  box.addView(button("查看官方启动说明",()->externalPage("https://shizuku.rikka.app/guide/setup/")));
  note(box,"已有 Root：主页可选 Root 并开始记录，在设备的 Root 管理器确认授权。Sui 可通过同一采集授权接口使用。安装轻帧不会让未 Root 的设备取得 Root。");
  note(box,"采集就绪后，主页‘采集状态’会显示 FPS、GPU、温度是否取得。GPU 受限不等于授权全部失效。");
  ScrollView scroll=new ScrollView(this);scroll.addView(box);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("采集授权向导").setView(scroll).setPositiveButton("完成",null).create();dialog.setOnDismissListener(d->{guideSummary=null;});dialog.show();
 }
 private void serviceAction(String a){if(MonitorService.running)startService(new Intent(this,MonitorService.class).setAction(a));else toast("尚未开始记录");}
 private void showSettings(){
  shell("设置","settings",false);LinearLayout c=scrolling(body);Config f=new Config(this);LinearLayout rates=card(c,"采样与悬浮窗");note(rates,"间隔单位为毫秒，数值越小采集越频繁；更改在下一次记录生效。");
  EditText frame=field(rates,"帧采样间隔（50—5000 ms）",""+f.framePeriod,"建议 100—250 ms"),hardware=field(rates,"硬件采样间隔（100—60000 ms）",""+f.hardwarePeriod,"建议 1000 ms"),temperature=field(rates,"温度采样间隔（500—60000 ms）",""+f.tempPeriod,"建议 2000—5000 ms");
  for(EditText input:new EditText[]{frame,hardware,temperature})input.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
  note(rates,"帧间隔小：读取更频繁、开销和文件量更高。间隔大：省开销，但系统帧缓冲有限，高帧率时可能漏帧，甚至无法形成有效窗口。500—1000 ms 要结合读取状态判断。");
  note(rates,"硬件间隔小：CPU、频率等变化更细，读取开销更高；间隔大：容易漏掉短峰值。温度建议 2—5 秒；系统更新较慢时，缩短间隔也可能重复读同一值。");
  rates.addView(button("保存采样间隔",()->{EditText[] fields={frame,hardware,temperature};int[] minima={50,100,500},maxima={5000,60000,60000},values=new int[3];for(int i=0;i<fields.length;i++){try{values[i]=SamplingIntervals.parse(fields[i].getText().toString(),minima[i],maxima[i]);fields[i].setError(null);}catch(IllegalArgumentException e){fields[i].setError(e.getMessage());fields[i].requestFocus();return;}}f.prefs.edit().putInt("framePeriod",values[0]).putInt("hardwarePeriod",values[1]).putInt("tempPeriod",values[2]).apply();toast("已保存；下一次记录生效");}));
  choice(rates,"目标帧率（用于长帧估算）",new String[]{"30","60","90","120","144","165"},new String[]{"30","60","90","120","144","165"},""+f.targetFps,"targetFps");rates.addView(button("应用低开销预设",()->{f.prefs.edit().putInt("framePeriod",250).putInt("hardwarePeriod",1000).putInt("tempPeriod",5000).apply();showSettings();toast("已设为帧 250ms、硬件 1s、温度 5s；下一次记录生效");}));
  note(rates,"实时仅保存原始数据与必要 FPS；停止后计算 Low 和分位数。无有效呈现窗口显示缺失，不以 0 FPS 计入平均。实际卡顿保留在逐帧数据。");toggle(rates,"记录帧率和逐帧时间","frames",f.frames);toggle(rates,"启用悬浮窗","overlay",f.overlay);rates.addView(button("选择悬浮窗指标",()->overlaySelection()));note(rates,"拖动悬浮窗移动；双击打开轻帧；长按隐藏。通知可继续显示或停止保存。");

  LinearLayout adapter=card(c,"GPU 适配与图层");EditText freq=field(adapter,"GPU 频率节点",f.gpuFreqPath,"/sys/… 或 /proc/…，空白自动探测");choice(adapter,"频率节点单位",new String[]{"Hz","kHz","MHz"},new String[]{"Hz","kHz","MHz"},f.gpuFreqUnit,"gpuFreqUnit");EditText load=field(adapter,"GPU 使用率节点",f.gpuLoadPath,"空白自动探测");choice(adapter,"GPU 使用率格式",new String[]{"百分比 / 首个数值","busy total 两个计数"},new String[]{"percent","busy_total"},f.gpuLoadFormat,"gpuLoadFormat");EditText temp=field(adapter,"GPU 温度节点",f.gpuTempPath,"空白自动探测"),layer=field(adapter,"固定 SurfaceFlinger 图层",f.layer,"空白自动选择");adapter.addView(button("保存适配设置",()->{String[] p={freq.getText().toString().trim(),load.getText().toString().trim(),temp.getText().toString().trim()};for(String v:p)if(!v.isEmpty()&&!Numbers.safeNode(v)){toast("节点必须位于 /sys 或 /proc，且不能包含 ..");return;}f.prefs.edit().putString("gpuFreqPath",p[0]).putString("gpuLoadPath",p[1]).putString("gpuTempPath",p[2]).putString("layer",layer.getText().toString().trim()).apply();toast("已保存，下次记录生效");}));gap(adapter,8);adapter.addView(button("查看可用图层",()->listLayers(layer)));
  LinearLayout d=card(c,"诊断与数据");d.addView(button("导出采集诊断",()->diagnose()));note(d,"诊断包括设备信息、节点权限、原始节点值和图层，用于适配 vivo / 联发科等设备。记录不设期限；支持完整 CSV、ZIP 和曲线图片导出。");pair(d,"版本",Config.VERSION+" · 测试版");note(d,"免费、无联网权限。原生界面，不使用 WebView。CPU/RAM 为系统指标；功率为电池侧估算。温度和 GPU 节点的可用性取决于系统权限。尚未在你的手机和平板上测量实际开销。");
 }
 private void overlaySelection(){String saved=new Config(this).prefs.getString("overlayKeys","fps,frameMs,cpuPct,gpuPct,gpuMHz,cpuC,gpuC,powerW");Set<String> selected=new LinkedHashSet<>(Arrays.asList(saved.split(",")));boolean[] checked=new boolean[Config.METRICS.length];for(int i=0;i<checked.length;i++)checked[i]=selected.contains(Config.METRICS[i]);new AlertDialog.Builder(this).setTitle("悬浮窗指标（最多 12 项）").setMultiChoiceItems(Config.LABELS,checked,(d,n,v)->checked[n]=v).setPositiveButton("保存",(d,n)->{ArrayList<String>a=new ArrayList<>();for(int i=0;i<checked.length;i++)if(checked[i])a.add(Config.METRICS[i]);if(a.isEmpty()||a.size()>12){toast("请选择 1 至 12 项");return;}new Config(this).prefs.edit().putString("overlayKeys",String.join(",",a)).apply();toast("已保存，下次记录生效");}).setNegativeButton("取消",null).show();}
 private void listLayers(EditText target){toast("正在读取图层…");java.util.function.Consumer<String> show=json->{try{JSONArray arr=new JSONObject(json).getJSONArray("layers");String[] names=new String[arr.length()];for(int i=0;i<names.length;i++)names[i]=arr.getString(i);if(!destroyed)new AlertDialog.Builder(this).setTitle("选择图层").setItems(names,(d,n)->target.setText(names[n])).setNegativeButton("取消",null).show();}catch(Exception e){toast(json);}};if(MonitorService.running&&!MonitorService.analyzing&&MonitorService.instance!=null){MonitorService.instance.layers(show);return;}String mode=new Config(this).mode;io.execute(()->{try(Backend b=Backend.connect(this,mode)){JSONObject req=new JSONObject();req.put("op","layers");String result=b.request(req).toString();ui.post(()->show.accept(result));}catch(Exception e){ui.post(()->toast(e.toString()));}});}

 private void diagnose(){toast("正在采集诊断…");java.util.function.Consumer<String> save=s->{io.execute(()->{try{File root=new File(getCacheDir(),"exports");root.mkdirs();File f=new File(root,"LightFrame-diagnostics.txt");try(Writer w=new OutputStreamWriter(new FileOutputStream(f),StandardCharsets.UTF_8)){String report=s;try{JSONObject diagnostic=new JSONObject(s);JSONObject last=new JSONObject(MonitorService.latest);if(last.length()==0||(last.optBoolean("paused")&&!last.has("cpuPct")&&!last.has("fps"))){File persisted=new File(getFilesDir(),"last-recording-sample.json");if(persisted.isFile())last=new JSONObject(new String(java.nio.file.Files.readAllBytes(persisted.toPath()),StandardCharsets.UTF_8));}diagnostic.put("lastRecordingSample",last);report=diagnostic.toString(2);}catch(Exception ignored){}w.write(Build.MANUFACTURER+" "+Build.MODEL+" Android "+Build.VERSION.RELEASE+"\n"+report);}ui.post(()->exportFile(f));}catch(Exception e){ui.post(()->toast(e.toString()));}});};if(MonitorService.running&&!MonitorService.analyzing&&MonitorService.instance!=null)MonitorService.instance.diagnose(save);else io.execute(()->{try(Backend b=Backend.connect(this,new Config(this).mode)){JSONObject req=new JSONObject();req.put("op","diagnose");req.put("frames",false);req.put("config",new Config(this).json());save.accept(b.request(req).toString(2));}catch(Exception e){save.accept(e.toString());}});}
 private void showRecords(){shell("记录", "records",false);LinearLayout c=scrolling(body);File root=new File(getFilesDir(),"sessions");File[] files=root.listFiles(File::isDirectory);if(files==null||files.length==0){note(c,"还没有记录。开始监测后，停止时会自动保存。");return;}Arrays.sort(files,(a,b)->b.getName().compareTo(a.getName()));for(File f:files){JSONObject j=readSummary(f);LinearLayout card=card(c,j.optString("title",f.getName()));pair(card,"时间",new java.text.SimpleDateFormat("MM-dd HH:mm:ss",Locale.getDefault()).format(new Date(j.optLong("startedUnixMs",f.lastModified()))));pair(card,"时长 / 采样",Config.elapsed(j.optDouble("durationSeconds",0))+" / "+j.optInt("samples",0));pair(card,"设备 / 采集器",j.optString("device","")+" · "+j.optString("backend",""));String status=j.optString("status","partial");if(!status.equals("complete"))note(card,status.equals("analyzing")?"正在计算统计；原始数据已保存，可打开查看":status.equals("recording")?"进行中或未正常结束；已有数据仍可查看":"不完整记录；打开时会从原始数据恢复统计");card.setOnClickListener(v->openSession(f));card.setContentDescription("打开记录 "+j.optString("title",f.getName()));}}
 private JSONObject readSummary(File dir){return SessionAnalysis.read(dir);}
 private void closeIndexes(){try{if(sampleIndex!=null)sampleIndex.close();}catch(Exception ignored){}try{if(frameIndex!=null)frameIndex.close();}catch(Exception ignored){}sampleIndex=frameIndex=null;}
 private void openSession(File f){
  session=f;selectedRow=selectedFrame=-1;selectedSample=null;samplePage=framePage=0;tab=0;rangeStats=null;viewport=null;summary=readSummary(f);shell(summary.optString("title",f.getName()),"session",true);
  TextView share=text("↗",24,INK);share.setGravity(Gravity.CENTER);share.setContentDescription("导出记录");share.setOnClickListener(v->exportMenu());header.addView(share,new LinearLayout.LayoutParams(dp(40),dp(50)));
  TextView del=text("⋮",24,INK);del.setGravity(Gravity.CENTER);del.setContentDescription("记录操作");del.setOnClickListener(v->sessionMenu());header.addView(del,new LinearLayout.LayoutParams(dp(32),dp(50)));
  HorizontalScrollView horizontal=new HorizontalScrollView(this);horizontal.setHorizontalScrollBarEnabled(false);LinearLayout tabs=row();historyTabs=tabs;
  for(int i=0;i<Config.TABS.length;i++){final int n=i;LinearLayout cell=column();TextView t=text(Config.TABS[i],12,ACCENT);t.setGravity(Gravity.CENTER);cell.addView(t,new LinearLayout.LayoutParams(dp(i>8?86:60),dp(36)));View line=new View(this);line.setBackgroundColor(i==0?ACCENT:0xFFDCD7E8);cell.addView(line,new LinearLayout.LayoutParams(-1,dp(2)));cell.setOnClickListener(v->{tab=n;if(sampleIndex!=null&&viewport!=null)renderTab();});tabs.addView(cell);}
  horizontal.addView(tabs);body.addView(horizontal);historyBody=column();body.addView(historyBody,new LinearLayout.LayoutParams(-1,0,1));content=scrolling(historyBody);final TextView loading=text("正在建立原始数据索引并恢复统计…",12,MUTED);content.addView(loading);
  final int sessionToken=sessionGeneration;final CsvIndex oldSamples=sampleIndex,oldFrames=frameIndex;sampleIndex=frameIndex=null;
  historyJob=historyIo.submit(()->{CsvIndex samples=null,frames=null;try{
   closeIndex(oldSamples);closeIndex(oldFrames);boolean active=MonitorService.running&&f.getAbsolutePath().equals(MonitorService.sessionPath);
   JSONObject result=active?SessionAnalysis.read(f):SessionAnalysis.ensure(f,(rows,frameRows)->{if(Thread.currentThread().isInterrupted())throw new CancellationException("已切换会话");ui.post(()->{if(!destroyed&&sessionToken==sessionGeneration)loading.setText("正在从原始数据恢复统计："+rows+" 次采样、"+frameRows+" 条呈现间隔…");});});samples=new CsvIndex(new File(f,"samples.csv"));File ff=new File(f,"frames.csv");if(ff.isFile())frames=new CsvIndex(ff);
   final CsvIndex ready=samples,readyFrames=frames;ui.post(()->{if(destroyed||sessionToken!=sessionGeneration){closeIndex(ready);closeIndex(readyFrames);return;}sampleIndex=ready;frameIndex=readyFrames;summary=result;double sampleEnd=Double.isFinite(ready.lastTime)?ready.lastTime:0,frameEnd=readyFrames!=null&&Double.isFinite(readyFrames.lastTime)?readyFrames.lastTime:0;viewport=new HistoryViewport(Math.max(sampleEnd,frameEnd));if(Double.isFinite(restoredBegin)&&Double.isFinite(restoredEnd)&&restoredEnd>restoredBegin)viewport.set(restoredBegin,restoredEnd);restoredBegin=restoredEnd=Double.NaN;rangeFrom=0;rangeTo=ready.count;renderTab();});
  }catch(Exception e){closeIndex(samples);closeIndex(frames);ui.post(()->{if(!destroyed&&sessionToken==sessionGeneration){content.removeAllViews();note(content,"读取失败："+e.getMessage());content.addView(button("重试读取",()->openSession(f)));}});}});
 }
 private static void closeIndex(CsvIndex source){if(source!=null)try{source.close();}catch(Exception ignored){}}
 private boolean current(int token,CsvIndex source){return !destroyed&&page.equals("session")&&token==generation&&source==sampleIndex;}
 private void renderTab(){
  if(sampleIndex==null||historyBody==null||viewport==null)return;if(historyJob!=null)historyJob.cancel(true);generation++;selection.request();dataGeneration++;charts.clear();rangeStats=null;chartHolder=null;detail=null;historyBody.removeAllViews();content=scrolling(historyBody);
  if(historyTabs!=null)for(int i=0;i<historyTabs.getChildCount();i++)((LinearLayout)historyTabs.getChildAt(i)).getChildAt(1).setBackgroundColor(i==tab?ACCENT:0xFFDCD7E8);
  historyControls();int token=generation;
  if(sampleIndex.count==0){note(content,"这份快照没有完整采样行。正在记录时请稍后刷新；旧记录请检查原始 CSV。");return;}
  if(tab==0){overview();loadHistory(token);return;}
  if(tab==9||tab==10){renderRows(tab==10,token);loadHistory(token);return;}
  note(content,"点选时刻查看全部指标；双指缩放，横向拖动。所有图窗同步。放大后会重新读取此区间原始数据。");chartHolder=column();content.addView(chartHolder);note(chartHolder,"正在读取此区间曲线…");detail=card(content,"该时刻 · 全部指标");note(detail,"正在读取原始采样…");
  showSample(selectedRow>=0?selectedRow:0);loadHistory(token);
 }
 private void historyControls(){
  LinearLayout controls=card(content,"时间浏览");rangeLabel=text("",12,INK);controls.addView(rangeLabel);updateRangeLabel();
  buttons(controls,"跳到准确时刻",()->timeDialog(false),"选择起止区间",()->timeDialog(true));
  LinearLayout r=row();String[] names={"放大 +","缩小 −","全部"};for(int i=0;i<3;i++){final int action=i;TextView b=button(names[i],()->{if(action==2)viewport.reset();else viewport.zoom(action==0?2:.5,.5);viewportChanged();viewportFinished();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(40),1);lp.setMargins(0,0,dp(4),0);r.addView(b,lp);}controls.addView(r);gap(controls,6);
  buttons(controls,"‹ 向前半窗",()->{viewport.pan(-(viewport.end-viewport.begin)/2);viewportChanged();viewportFinished();},"向后半窗 ›",()->{viewport.pan((viewport.end-viewport.begin)/2);viewportChanged();viewportFinished();});
  historyState=text("正在计算区间全量统计…",12,MUTED);controls.addView(historyState);gap(controls,6);controls.addView(button("查看区间全部统计 / 缺失原因",()->rangeDetails()));
  String status=summary.optString("status","");if(status.equals("analyzing")||status.equals("recording")){note(controls,status.equals("analyzing")?"停止后的全记录统计正在计算；当前为原始数据快照。":"当前为记录快照；后续数据请刷新读取。");controls.addView(button("刷新记录快照",()->openSession(session)));}
 }
 private void updateRangeLabel(){if(rangeLabel!=null&&viewport!=null)rangeLabel.setText("录制经过 "+HistoryTime.elapsed(viewport.begin)+" — "+HistoryTime.elapsed(viewport.end)+"\n"+HistoryTime.clock(summary.optLong("startedUnixMs"),viewport.begin)+" — "+HistoryTime.clock(summary.optLong("startedUnixMs"),viewport.end));}
 private void viewportChanged(){selection.request();updateRangeLabel();rangeStats=null;if(historyState!=null)historyState.setText("区间已改变，松手后更新原始数据与统计…");for(HistoryChart chart:charts)chart.invalidate();}
 private void viewportFinished(){if(tab==9||tab==10){samplePage=framePage=0;renderTab();}else loadHistory(generation);}
 private String[] historyKeys(){LinkedHashSet<String> keys=new LinkedHashSet<>(Arrays.asList(Config.METRICS));for(String key:sampleIndex.header)if(key.matches("cpu[0-9]+MHz"))keys.add(key);return keys.toArray(new String[0]);}
 private void loadHistory(int token){
  if(historyJob!=null)historyJob.cancel(true);final int request=++dataGeneration,defaultStamp=selection.stamp();final CsvIndex source=sampleIndex,frames=frameIndex;final double begin=viewport.begin,end=viewport.end;final int selectedTab=tab;final LinearLayout holder=chartHolder;final String[] keys=historyKeys();
  if(historyState!=null)historyState.setText("正在读取区间原始数据并计算全部统计…");
  historyJob=historyIo.submit(()->{try{HistoryRange stats=HistoryRange.load(source,frames,begin,end,keys);ChartData[] data=holder==null?null:ChartData.load(source,Config.GROUPS[selectedTab],begin,end);
   ui.post(()->{if(!current(token,source)||request!=dataGeneration)return;rangeStats=stats;rangeFrom=stats.from;rangeTo=stats.to;if(historyState!=null)historyState.setText("区间包含 "+stats.rows+" 次原始采样、"+stats.frameRows+" 条呈现间隔；暂停 "+stats.pausedRows+" 次。统计使用全部有效值。");
    if(holder!=null){holder.removeAllViews();charts.clear();for(ChartData d:data){if(d.count==0&&selectedTab==3&&!d.key.equals("gpuMHz"))continue;HistoryChart chart=new HistoryChart(this,d,viewport);chart.onSelect=t->selectTime(t);chart.onViewportChanged=()->viewportChanged();chart.onViewportFinished=()->viewportFinished();LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,adaptiveChartHeight(chart));lp.setMargins(0,0,0,dp(8));holder.addView(chart,lp);charts.add(chart);if(d.count==0)note(holder,Config.label(d.key)+"："+stats.missingReasons.getOrDefault(d.key,stats.rows==0?"此区间没有采样":"此区间只有暂停采样"));}if(charts.isEmpty())note(holder,"此区间未记录频率数据，请查看区间统计和原始采样原因。");
     if(stats.from<stats.to){if(selectedSample!=null&&selectedRow>=stats.from&&selectedRow<stats.to){for(HistoryChart chart:charts)chart.select(CsvIndex.time(selectedSample),historyValue(source,selectedSample,chart.data.key));}else if(selection.current(defaultStamp))showSample(stats.from);}else if(detail!=null){detail.removeAllViews();note(detail,"此区间没有采样。扩大区间或跳到其他时刻。");}}
   });
  }catch(Exception e){if(e instanceof InterruptedIOException||Thread.currentThread().isInterrupted())return;ui.post(()->{if(current(token,source)&&request==dataGeneration){if(historyState!=null)historyState.setText("读取失败："+e.getMessage()+"；可刷新快照重试");if(holder!=null){holder.removeAllViews();note(holder,"曲线读取失败："+e.getMessage());}}});}});
 }
 private void timeDialog(boolean interval){
  LinearLayout box=column();box.setPadding(dp(18),dp(8),dp(18),dp(8));Spinner mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"录制经过时间","当地日期 / 时钟时间"}));box.addView(mode);EditText first=field(box,interval?"开始（包含该时刻）":"查看时刻",HistoryTime.elapsed(interval?viewport.begin:viewport.begin),"秒、分:秒或时:分:秒.毫秒");EditText last=interval?field(box,"结束（包含该时刻）",HistoryTime.elapsed(viewport.end),"结束时间"):null;note(box,"经过时间可输入 12.345 或 00:12.345；当地时间可输入 yyyy-MM-dd HH:mm:ss.SSS 或 HH:mm:ss.SSS。点选将显示最近原始行，并标明实际时间。");
  mode.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> p,View v,int n,long id){boolean wall=n==1;first.setText(wall?HistoryTime.clock(summary.optLong("startedUnixMs"),viewport.begin):HistoryTime.elapsed(viewport.begin));if(last!=null)last.setText(wall?HistoryTime.clock(summary.optLong("startedUnixMs"),viewport.end):HistoryTime.elapsed(viewport.end));}public void onNothingSelected(AdapterView<?> p){}});
  AlertDialog dialog=new AlertDialog.Builder(this).setTitle(interval?"准确选择区间":"跳到准确时刻").setView(box).setPositiveButton("查看",null).setNegativeButton("取消",null).create();dialog.setOnShowListener(v->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(b->{try{boolean wall=mode.getSelectedItemPosition()==1;double a=HistoryTime.parse(first.getText().toString(),wall,summary.optLong("startedUnixMs"));double z=interval?HistoryTime.parse(last.getText().toString(),wall,summary.optLong("startedUnixMs")):a;a=HistoryTime.normalizeBoundary(a,viewport.fullEnd);z=HistoryTime.normalizeBoundary(z,viewport.fullEnd);if(interval){if(z<=a)throw new IllegalArgumentException("结束时间必须大于开始时间");viewport.set(a,z);samplePage=framePage=0;renderTab();}else{if(a<viewport.begin||a>viewport.end){double span=viewport.end-viewport.begin;viewport.set(a-span/2,a+span/2);viewportChanged();viewportFinished();}if(tab==0){tab=9;renderTab();}selectTime(a);}dialog.dismiss();}catch(Exception e){first.setError(e.getMessage());}}));dialog.show();
 }
 private void rangeDetails(){
  HistoryRange stats=rangeStats;if(stats==null){toast("正在读取区间数据，请稍候");return;}LinearLayout box=column();box.setPadding(dp(16),dp(10),dp(16),dp(12));note(box,"区间 "+HistoryTime.elapsed(stats.begin)+" — "+HistoryTime.elapsed(stats.end)+"；"+stats.rows+" 次原始采样。暂停行不参加均值；空值不当作零。硬件值按原记录采样口径统计。");
  for(Map.Entry<String,HistoryRange.Metric> e:stats.metrics.entrySet()){String key=e.getKey();HistoryRange.Metric m=e.getValue();LinearLayout c=card(box,key.equals("interval_ms")?"实际呈现间隔 (ms)":Config.label(key));pair(c,"有效 / 缺失 / 暂停",m.valid+" / "+m.missing+" / "+m.paused);pair(c,"平均 / 最低 / 最高",Numbers.display(m.avg,6)+" / "+Numbers.display(m.min,6)+" / "+Numbers.display(m.max,6)+" "+Config.unit(key));pair(c,"标准差（样本）",Numbers.display(m.stdDev,6));LinkedHashMap<String,Long> reasons=stats.reasonCounts.get(key);if(reasons!=null)for(Map.Entry<String,Long> reason:reasons.entrySet())note(c,reason.getValue()+" 次："+reason.getKey());else if(m.valid==0)note(c,m.paused>0?"此区间仅有暂停行":"此区间未取得此指标");}
  ScrollView scroll=new ScrollView(this);scroll.addView(box);new AlertDialog.Builder(this).setTitle("区间全部指标 · 全量统计").setView(scroll).setPositiveButton("关闭",null).show();
 }
 private void overview(){if(summary.optString("status").equals("analyzing"))note(content,"全记录 Low / 分位数仍在后台计算；下方缺失值表示待计算。区间统计可直接读取原始数据。");LinearLayout fps=card(content,"全记录 FPS 汇总");JSONObject st=summary.optJSONObject("statistics"),f=st==null?null:st.optJSONObject("fps");pair(fps,"平均 / 最低 / 最高",f==null?"—":Numbers.display(f.optDouble("avg"),1)+" / "+Numbers.display(f.optDouble("min"),1)+" / "+Numbers.display(f.optDouble("max"),1));pair(fps,"P1 / P5（FPS 采样值）",f==null?"—":Numbers.display(f.optDouble("p1"),1)+" / "+Numbers.display(f.optDouble("p5"),1));pair(fps,"FPS 波动（标准差）",f==null?"—":Numbers.display(f.optDouble("stdDev"),2));pair(fps,"1% Low / 0.1% Low",Numbers.display(summary.optDouble("low1Pct"),1)+" / "+Numbers.display(summary.optDouble("low01Pct"),1));pair(fps,"捕获帧区间数",summary.has("capturedIntervals")?""+summary.optLong("capturedIntervals"):"—");pair(fps,"捕获帧平均 FPS",Numbers.display(summary.optDouble("capturedFrameAverageFps"),1));if(summary.optLong("excludedUnavailableFpsZeros",0)>0)note(fps,"已排除无有效窗口的 0 FPS："+summary.optLong("excludedUnavailableFpsZeros")+" 次；原始行和逐帧卡顿仍保留。");LinearLayout other=card(content,"全记录硬件均值");for(String k:new String[]{"cpuPct","gpuPct","gpuMHz","ramUsedMB","powerW","cpuC","gpuC","socC","batteryC","monitorCpuPct","monitorRssMB"}){JSONObject s=st==null?null:st.optJSONObject(k);pair(other,Config.label(k),Config.format(k,s==null?Double.NaN:s.optDouble("avg")));}LinearLayout longframes=card(content,"全记录长帧估算");pair(longframes,"长帧 / 严重长帧",summary.has("longFramesEstimate")?summary.optLong("longFramesEstimate")+" / "+summary.optLong("bigLongFramesEstimate"):"—");note(longframes,"按目标帧预算的 1.5 倍 / 3 倍估算，不等同于官方 Jank 或商业工具口径。");LinearLayout data=card(content,"记录信息");pair(data,"原始采样数",""+sampleIndex.count);pair(data,"时长",Config.elapsed(summary.optDouble("durationSeconds",0)));pair(data,"采集方式",summary.optString("backend","")+" · UID "+summary.optInt("uid"));pair(data,"设备",summary.optString("device",""));note(data,"空值表示未取得。硬件 / 温度各自更新，采样明细会显示数据距今。曲线在长记录中按最小和最大值合并绘制，原始值全部保留。");data.addView(button("从第一条开始查看",()->{tab=9;renderTab();}));}
 private void selectTime(double t){
  final CsvIndex source=tab==10?frameIndex:sampleIndex;if(source==null||source.count==0){toast("此区间没有原始数据");return;}final CsvIndex sessionSource=sampleIndex;final int token=generation,request=selection.request();final boolean frames=tab==10;final double begin=viewport.begin,end=viewport.end;
  selectionIo.execute(()->{try{int from=source.lowerBound(begin),to=source.upperBound(end);if(from>=to){ui.post(()->{if(current(token,sessionSource))toast("此区间没有采样，请扩大区间");});return;}int index=Math.max(from,Math.min(to-1,source.nearest(t)));String[] values=source.row(index);
   ui.post(()->{if(!current(token,sessionSource)||!selection.current(request))return;if(frames){selectedFrame=index;framePage=(index-from)/50;renderTab();}else if(tab==9){selectedRow=index;selectedSample=values;samplePage=(index-from)/50;renderTab();}else{applySample(source,values,index,t);revealDetails();}});
  }catch(Exception e){ui.post(()->{if(current(token,sessionSource)&&selection.current(request))detailError("时刻读取失败："+e.getMessage());});}});
 }
 private void showSample(int n){
  if(sampleIndex==null||sampleIndex.count==0||detail==null)return;final int requested=Math.max(0,Math.min(sampleIndex.count-1,n)),token=generation,request=selection.request();final CsvIndex source=sampleIndex;final double begin=viewport.begin,end=viewport.end;
  selectionIo.execute(()->{try{int from=source.lowerBound(begin),to=source.upperBound(end);if(from>=to){ui.post(()->{if(current(token,source)&&selection.current(request))detailError("此区间没有原始采样，请扩大范围。");});return;}int index=Math.max(from,Math.min(to-1,requested));String[] values=source.row(index);ui.post(()->{if(current(token,source)&&selection.current(request))applySample(source,values,index,Double.NaN);});}catch(Exception e){ui.post(()->{if(current(token,source)&&selection.current(request))detailError("采样读取失败："+e.getMessage());});}});
 }
 private void applySample(CsvIndex source,String[] values,int index,double requested){
  selectedRow=index;selectedSample=values;double time=CsvIndex.time(values);for(HistoryChart chart:charts)chart.select(time,historyValue(source,values,chart.data.key));if(detail!=null){detail.removeAllViews();sampleDetails(detail,source,values,index);if(Double.isFinite(requested))note(detail,"点选时间 "+HistoryTime.elapsed(requested)+"；显示最近原始行，时间差 "+Numbers.display(Math.abs(time-requested)*1000,3)+" ms。");}
 }
 private void revealDetails(){if(detail!=null&&content!=null&&content.getParent() instanceof ScrollView){final LinearLayout box=detail;content.post(()->{if(box==detail&&content.getParent() instanceof ScrollView)((ScrollView)content.getParent()).smoothScrollTo(0,Math.max(0,box.getTop()-dp(8)));});}}
 private void detailError(String error){if(detail!=null){detail.removeAllViews();note(detail,error);detail.addView(button("重试本次采样",()->showSample(selectedRow>=0?selectedRow:0)));}}
 private double historyValue(CsvIndex source,String[] row,String key){double raw=source.value(row,key);return key.equals("fps")?new FpsSampleValidity(source.header).value(raw,row):raw;}
 private void sampleDetails(LinearLayout box,CsvIndex source,String[] values,int index){
  double time=CsvIndex.time(values);box.addView(text("第 "+(index+1)+" / "+source.count+" 次原始采样 · "+HistoryTime.elapsed(time),14,ACCENT));note(box,HistoryTime.clock(summary.optLong("startedUnixMs"),time));gap(box,4);
  buttons(box,"‹ 上一条",()->showSample(index-1),"下一条 ›",()->showSample(index+1));box.addView(button("全部原始字段 / 精确数值（可复制）",()->rawValues(source,values)));gap(box,6);
  boolean paused=false;int p=source.column("paused");if(p>=0&&p<values.length)paused="true".equalsIgnoreCase(values[p]);if(paused)note(box,"此行处于暂停状态，原始值仍可查看，但不计入区间统计。");
  LinkedHashSet<String> keys=new LinkedHashSet<>(Arrays.asList(Config.METRICS));for(String key:source.header)if(key.matches("cpu[0-9]+MHz"))keys.add(key);
  FpsSampleValidity fpsValidity=new FpsSampleValidity(source.header);for(String key:keys){double v=source.value(values,key);boolean invalidZero=key.equals("fps")&&fpsValidity.invalidZero(v,values);pair(box,Config.label(key),invalidZero?"原始 0（窗口无效）":Config.format(key,v));if(invalidZero)note(box,FpsSampleValidity.reason());else if(!Double.isFinite(v))note(box,HistoryRange.missingReason(source,values,key));}
  for(String key:new String[]{"paused","charging","thermalStatus","frameStatus","frameWindowReady","frameWindowStale","frameDataAgeMs","frameWindowSpanMs","captureGapCount","foregroundPackage","foregroundStatus","frameSourceVerified","gpuLoadStatus","gpuFrequencyStatus","cpuTemperatureStatus","gpuTemperatureStatus","socTemperatureStatus","thermalServiceStatus","thermalServiceSource","frameAvailable","frameProbeCount","frameCandidateCount","frameProbeFailures","layer","longFramesEstimate","bigLongFramesEstimate","unix_ms"}){int i=source.column(key);if(i>=0&&i<values.length&&!values[i].isEmpty())note(box,statusLabel(key)+"："+values[i]);}
 }
 private void rawValues(CsvIndex source,String[] r){StringBuilder s=new StringBuilder();for(int i=0;i<source.header.length;i++){String k=source.header[i];s.append(Config.label(k)).append(" [").append(k).append("]\n").append(i<r.length&&!r[i].isEmpty()?r[i]:"未取得").append(" ").append(Config.unit(k)).append("\n\n");}TextView t=text(s.toString(),13,INK);t.setTextIsSelectable(true);t.setPadding(dp(18),dp(12),dp(18),dp(12));ScrollView sc=new ScrollView(this);sc.addView(t);new AlertDialog.Builder(this).setTitle("原始采样值（可复制）").setView(sc).setPositiveButton("关闭",null).show();}
 private String statusLabel(String s){switch(s){case "paused":return "暂停标记";case "charging":return "充电中";case "thermalStatus":return "系统热状态";case "frameStatus":return "帧来源 / 状态";case "gpuLoadStatus":return "GPU 使用率来源";case "gpuFrequencyStatus":return "GPU 频率来源";case "cpuTemperatureStatus":return "CPU 温度来源";case "gpuTemperatureStatus":return "GPU 温度来源";case "socTemperatureStatus":return "SoC 温度来源";case "thermalServiceStatus":return "系统温度服务状态";case "thermalServiceSource":return "系统温度读数来源";case "frameWindowReady":return "滚动帧窗口已就绪";case "frameDataAgeMs":return "最新呈现帧距今（ms）";case "frameWindowSpanMs":return "滚动窗口跨度（ms）";case "captureGapCount":return "已检测缓冲漏采次数";case "foregroundPackage":return "当时前台应用";case "foregroundStatus":return "前台应用读取状态";case "frameSourceVerified":return "图层归属验证";case "frameAvailable":return "帧接口可用";case "frameProbeCount":return "已尝试图层";case "frameCandidateCount":return "候选图层数";case "frameProbeFailures":return "图层读取失败数";case "layer":return "图层";case "longFramesEstimate":return "累计长帧估算";case "bigLongFramesEstimate":return "累计严重长帧估算";case "unix_ms":return "时间戳（ms）";default:return s;}}
 private void renderRows(boolean frames,int token){
  final CsvIndex source=frames?frameIndex:sampleIndex,sessionSource=sampleIndex;if(source==null||source.count==0){note(content,frames?"此记录没有逐帧数据。未启用帧采集、接口无权限或未返回帧时不会生成有效逐帧行。":"此记录没有完整采样行。");return;}
  final double begin=viewport.begin,end=viewport.end;final int requestedPage=frames?framePage:samplePage,defaultStamp=selection.stamp();final LinearLayout controls=card(content,frames?"逐帧时间 · 原始记录":"采样明细 · 原始记录");note(controls,"正在读取区间内原始数据…");
  final LinearLayout list=card(content,frames?"序号 · 时间 · 呈现间隔":"序号 · 时间 · FPS · CPU · GPU");note(list,"正在加载…");detail=card(content,frames?"本帧详情":"该时刻 · 全部指标");note(detail,"正在加载第一条原始数据…");
  selectionIo.execute(()->{try{int rangeStart=source.lowerBound(begin),rangeEnd=source.upperBound(end),total=rangeEnd-rangeStart;int pageNum=Math.min(Math.max(0,requestedPage),Math.max(0,(total-1)/50)),from=rangeStart+pageNum*50,to=Math.min(rangeEnd,from+50);ArrayList<String[]> rows=new ArrayList<>();source.scan(from,to,(n,row)->rows.add(row));
   ui.post(()->{if(!current(token,sessionSource))return;controls.removeAllViews();list.removeAllViews();if(total==0){note(controls,"此区间没有"+(frames?"逐帧":"采样")+"数据。扩大区间或点“全部”。");detail.removeAllViews();note(detail,"此区间无原始行可显示。");return;}if(frames)framePage=pageNum;else samplePage=pageNum;
    pair(controls,"区间原始行 / 当前页",total+" / "+(pageNum+1)+"—"+((total+49)/50));pair(controls,"原始序号",(from+1)+" — "+to+" / "+source.count);
    buttons(controls,"‹ 上一页",()->{if(frames)framePage=Math.max(0,pageNum-1);else samplePage=Math.max(0,pageNum-1);renderTab();},"下一页 ›",()->{if(frames)framePage=Math.min((total-1)/50,pageNum+1);else samplePage=Math.min((total-1)/50,pageNum+1);renderTab();});
    LinearLayout jump=row();EditText number=new EditText(this);number.setHint("原始序号（区间内）");number.setTextSize(13);number.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);jump.addView(number,new LinearLayout.LayoutParams(0,dp(42),1));jump.addView(button("跳转",()->{try{int n=Integer.parseInt(number.getText().toString())-1;if(n<rangeStart||n>=rangeEnd)throw new IllegalArgumentException();if(frames){framePage=(n-rangeStart)/50;selectedFrame=n;}else{samplePage=(n-rangeStart)/50;selectedRow=n;}renderTab();}catch(Exception e){number.setError("请输入 "+(rangeStart+1)+" — "+rangeEnd+" 的原始序号");}}));controls.addView(jump);
    note(controls,frames?"间隔来自实际呈现时间。未返回的帧无法补回；空值不填零。":"每一行来自原始 CSV，区间内全量可翻页。点行显示所有指标及读取原因。");
    for(int x=0;x<rows.size();x++){final int index=from+x;final String[] values=rows.get(x);String label=String.format(Locale.US,"#%d   %s   ",index+1,Config.elapsed(CsvIndex.time(values)));label+=frames?Numbers.display(source.value(values,"interval_ms"),3)+" ms":Numbers.display(source.value(values,"fps"),1)+"   "+Numbers.display(source.value(values,"cpuPct"),1)+"%   "+Numbers.display(source.value(values,"gpuPct"),1)+"%";
     TextView row=text(label,12,INK);row.setPadding(0,dp(11),0,dp(11));row.setBackground(round(index==(frames?selectedFrame:selectedRow)?0xFFD6D5EC:CARD,3));row.setOnClickListener(v->{selection.request();if(frames)applyFrame(source,values,index);else applySample(source,values,index,Double.NaN);revealDetails();});list.addView(row);View line=new View(this);line.setBackgroundColor(0xFFD3D0E1);list.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));
    }
    int selected=frames?selectedFrame:selectedRow;int index=selected>=from&&selected<to?selected:from;if(selection.current(defaultStamp)){if(frames)applyFrame(source,rows.get(index-from),index);else applySample(source,rows.get(index-from),index,Double.NaN);}
   });
  }catch(Exception e){ui.post(()->{if(current(token,sessionSource)){controls.removeAllViews();note(controls,"读取失败："+e.getMessage());list.removeAllViews();note(list,"可刷新记录快照后重试。");detailError("无法读取原始数据："+e.getMessage());}});}});
 }
 private void showFrame(int n){
  final CsvIndex source=frameIndex,sessionSource=sampleIndex;if(source==null||source.count==0||detail==null)return;final int requested=Math.max(0,Math.min(source.count-1,n)),token=generation,request=selection.request();final double begin=viewport.begin,end=viewport.end;
  selectionIo.execute(()->{try{int from=source.lowerBound(begin),to=source.upperBound(end);if(from>=to){ui.post(()->{if(current(token,sessionSource)&&selection.current(request))detailError("此区间没有原始逐帧数据。");});return;}int index=Math.max(from,Math.min(to-1,requested));String[] values=source.row(index);ui.post(()->{if(current(token,sessionSource)&&selection.current(request))applyFrame(source,values,index);});}catch(Exception e){ui.post(()->{if(current(token,sessionSource)&&selection.current(request))detailError("逐帧读取失败："+e.getMessage());});}});
 }
 private void applyFrame(CsvIndex source,String[] values,int index){
  selectedFrame=index;if(detail==null)return;detail.removeAllViews();double time=CsvIndex.time(values),interval=source.value(values,"interval_ms");detail.addView(text("第 "+(index+1)+" / "+source.count+" 条呈现间隔 · "+HistoryTime.elapsed(time),14,ACCENT));note(detail,HistoryTime.clock(summary.optLong("startedUnixMs"),time));buttons(detail,"‹ 上一帧",()->showFrame(index-1),"下一帧 ›",()->showFrame(index+1));pair(detail,"帧间隔",Numbers.display(interval,6)+" ms");pair(detail,"瞬时帧率（间隔倒数）",Numbers.display(interval>0?1000/interval:Double.NaN,6)+" fps");detail.addView(button("查看全部原始字段",()->rawValues(source,values)));for(int i=0;i<source.header.length&&i<values.length;i++)note(detail,source.header[i]+"："+(values[i].isEmpty()?"未取得":values[i]));
 }
 private void sessionMenu(){new AlertDialog.Builder(this).setItems(new String[]{"刷新当前记录快照","删除记录"},(d,n)->{if(n==0)openSession(session);else{if(MonitorService.running&&session.getAbsolutePath().equals(MonitorService.sessionPath)){toast("请先停止正在记录的会话");return;}new AlertDialog.Builder(this).setTitle("删除此记录？").setMessage("这会删除该记录的全部原始数据。").setNegativeButton("取消",null).setPositiveButton("删除",(dialog,which)->{File f=session;generation++;io.execute(()->{closeIndexes();boolean ok=deleteTree(f);ui.post(()->{toast(ok?"已删除":"删除失败");showRecords();});});}).show();}}).show();}
 private boolean deleteTree(File f){File[] a=f.listFiles();if(a!=null)for(File child:a)if(!deleteTree(child))return false;return f.delete();}
 private void exportMenu(){if(session==null)return;new AlertDialog.Builder(this).setTitle("导出").setItems(new String[]{"全部数据 ZIP","全部采样 CSV","全部逐帧 CSV","当前区间采样 CSV","当前区间逐帧 CSV","当前曲线 PNG"},(d,n)->{if(n==1)exportFile(new File(session,"samples.csv"));else if(n==2)exportFile(new File(session,"frames.csv"));else if(n==3||n==4)exportRange(n==4);else if(n==5){if(charts.isEmpty()){toast("先打开一个指标曲线");return;}if(rangeStats==null){toast("正在更新区间曲线，请稍后导出");return;}String[] labels=new String[charts.size()];for(int i=0;i<labels.length;i++)labels[i]=Config.label(charts.get(i).data.key);new AlertDialog.Builder(this).setTitle("选择曲线").setItems(labels,(dialog,x)->makeImage(charts.get(x))).show();}else makeZip();}).show();}
 private void exportRange(boolean frames){
  final CsvIndex source=frames?frameIndex:sampleIndex;if(source==null){toast("此记录未保存逐帧数据");return;}final double begin=viewport.begin,end=viewport.end;final File folder=session;toast("正在导出此区间的全部原始数值…");io.execute(()->{try{File dest=new File(getCacheDir(),"exports");dest.mkdirs();File out=new File(dest,folder.getName()+"_"+(frames?"frames":"samples")+"_"+Math.round(begin*1000)+"-"+Math.round(end*1000)+"ms.csv");try(Writer writer=new BufferedWriter(new OutputStreamWriter(new FileOutputStream(out),StandardCharsets.UTF_8))){writer.write(CsvIndex.encode(source.header)+"\n");source.scan(source.lowerBound(begin),source.upperBound(end),(n,row)->{try{writer.write(CsvIndex.encode(row)+"\n");}catch(IOException e){throw new UncheckedIOException(e);}});}ui.post(()->exportFile(out));}catch(Exception e){ui.post(()->toast("区间导出失败："+e.getMessage()));}});
 }
 private void makeZip(){File src=session;toast("正在打包完整记录…");io.execute(()->{try{File dest=new File(getCacheDir(),"exports");dest.mkdirs();File zip=new File(dest,src.getName()+".zip");try(ZipOutputStream out=new ZipOutputStream(new BufferedOutputStream(new FileOutputStream(zip)))){File[] files=src.listFiles(File::isFile);if(files!=null)for(File f:files)if(!f.getName().endsWith(".tmp")){out.putNextEntry(new ZipEntry(f.getName()));try(InputStream in=new FileInputStream(f)){byte[] b=new byte[32768];for(int n;(n=in.read(b))!=-1;)out.write(b,0,n);}out.closeEntry();}}ui.post(()->exportFile(zip));}catch(Exception e){ui.post(()->toast(e.toString()));}});}
 private int adaptiveChartHeight(HistoryChart chart){
  int windowWidth=historyBody!=null&&historyBody.getWidth()>0?historyBody.getWidth():root.getWidth()-root.getPaddingLeft()-root.getPaddingRight();int width=chart.getWidth()>0?chart.getWidth():Math.max(dp(160),windowWidth-dp(24));int height=historyBody!=null?historyBody.getHeight():body.getHeight();return chart.recommendedHeight(width,height);
 }
 private void updateChartHeights(){if(destroyed||!page.equals("session"))return;for(HistoryChart chart:charts){android.view.ViewGroup.LayoutParams lp=chart.getLayoutParams();if(lp!=null){int height=adaptiveChartHeight(chart);if(lp.height!=height){lp.height=height;chart.setLayoutParams(lp);}chart.invalidate();}}}
 private void imageText(Canvas c,android.text.TextPaint paint,String s,float x,float y,int maxWidth){String fit=android.text.TextUtils.ellipsize(s,paint,maxWidth,android.text.TextUtils.TruncateAt.END).toString();c.drawText(fit,x,y,paint);}
 private void makeImage(HistoryChart chart){
  File dest=new File(getCacheDir(),"exports");dest.mkdirs();File out=new File(dest,session.getName()+"_"+chart.data.key+".png");int width=1200,margin=28,headerHeight=118,chartWidth=width-2*margin,chartHeight=chart.recommendedHeight(chartWidth,900,2f,2f),height=headerHeight+chartHeight+104;
  Bitmap image=Bitmap.createBitmap(width,height,Bitmap.Config.ARGB_8888);try{Canvas c=new Canvas(image);c.drawColor(BG);android.text.TextPaint p=new android.text.TextPaint(Paint.ANTI_ALIAS_FLAG);p.setColor(INK);p.setTextSize(30);imageText(c,p,summary.optString("title","轻帧记录"),margin,42,chartWidth);p.setTextSize(20);p.setColor(MUTED);imageText(c,p,summary.optString("device","")+" · "+summary.optString("backend","")+" · "+sampleIndex.count+" 次原始采样",margin,74,chartWidth);imageText(c,p,"录制经过 "+HistoryTime.elapsed(chart.viewport.begin)+" — "+HistoryTime.elapsed(chart.viewport.end),margin,101,chartWidth);
   c.save();c.translate(margin,headerHeight);chart.render(c,chartWidth,chartHeight,2f,2f);c.restore();p.setTextSize(19);imageText(c,p,"轻帧 "+Config.VERSION+" · 数字纵轴 / 原始单位 · 区间统计使用全部有效原始样本",margin,headerHeight+chartHeight+36,chartWidth);imageText(c,p,"空值不填零；曲线合并绘制；点选的精确数值及全部原始记录保存在 CSV",margin,headerHeight+chartHeight+65,chartWidth);
   try(OutputStream stream=new FileOutputStream(out)){image.compress(Bitmap.CompressFormat.PNG,100,stream);}exportFile(out);
  }catch(Exception e){toast(e.toString());}finally{image.recycle();}
 }
 private String mime(File f){return f.getName().endsWith(".csv")?"text/csv":f.getName().endsWith(".png")?"image/png":f.getName().endsWith(".txt")?"text/plain":"application/zip";}
 private void exportFile(File f){if(!f.isFile()){toast("文件尚未生成");return;}new AlertDialog.Builder(this).setTitle(f.getName()).setItems(new String[]{"保存到文件","分享"},(d,n)->{try{if(n==0){pendingExport=f;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime(f));i.putExtra(Intent.EXTRA_TITLE,f.getName());startActivityForResult(i,201);}else{Uri uri=ExportProvider.uri(this,f);Intent i=new Intent(Intent.ACTION_SEND);i.setType(mime(f));i.putExtra(Intent.EXTRA_STREAM,uri);i.setClipData(ClipData.newRawUri(f.getName(),uri));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"分享记录"));}}catch(Exception e){toast(e.toString());}}).show();}
 @Override protected void onActivityResult(int code,int result,Intent data){super.onActivityResult(code,result,data);if(code==201&&result==RESULT_OK&&data!=null&&data.getData()!=null&&pendingExport!=null){Uri uri=data.getData();File src=pendingExport;pendingExport=null;io.execute(()->{try(InputStream in=new FileInputStream(src);OutputStream out=getContentResolver().openOutputStream(uri)){if(out==null)throw new IOException("无法打开目标文件");byte[] b=new byte[32768];for(int n;(n=in.read(b))!=-1;)out.write(b,0,n);ui.post(()->toast("已保存"));}catch(Exception e){ui.post(()->toast("保存失败："+e));}});}}
 @Override public void onBackPressed(){if(page.equals("session"))showRecords();else if(!page.equals("home"))showHome();else super.onBackPressed();}
 private void toast(String s){if(!destroyed)Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
