package com.lightframe.monitor;

import android.app.*;import android.content.*;import android.graphics.*;import android.os.*;import android.provider.Settings;import android.view.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
public final class MonitorService extends Service {
 public static volatile boolean running,paused,hidden,analyzing;public static volatile String latest="{}",status="尚未开始",sessionPath="";public static volatile MonitorService instance;
 private final Handler main=new Handler(Looper.getMainLooper());private HandlerThread thread;private Handler work;private Backend backend;private SessionRecorder recorder;private Config config;private JSONObject cached=new JSONObject(),requestConfig;private WindowManager windows;private Overlay view;private WindowManager.LayoutParams layout;private boolean stopping,screenPaused;private long hwNs,tempNs,tempPollNs,cpuNs,appCpu,helperCpu;private int voltage,level;private double batteryC=Double.NaN;private boolean charging;private String notice="";private String[] overlayKeys;private long lastOverlayDraw;
 private final BroadcastReceiver battery=new BroadcastReceiver(){public void onReceive(Context c,Intent i){voltage=i.getIntExtra(BatteryManager.EXTRA_VOLTAGE,0);int scale=i.getIntExtra(BatteryManager.EXTRA_SCALE,100);level=100*i.getIntExtra(BatteryManager.EXTRA_LEVEL,0)/Math.max(1,scale);int t=i.getIntExtra(BatteryManager.EXTRA_TEMPERATURE,Integer.MIN_VALUE);batteryC=t==Integer.MIN_VALUE?Double.NaN:t/10d;charging=i.getIntExtra(BatteryManager.EXTRA_PLUGGED,0)!=0;}};
 private final Runnable tick=new Runnable(){public void run(){if(stopping)return;long start=System.nanoTime();try{
  PowerManager power=(PowerManager)getSystemService(POWER_SERVICE);boolean suspend=paused||!power.isInteractive();
  if(suspend){if(!screenPaused){recorder.pause(paused?"手动暂停":"息屏暂停");screenPaused=true;status=paused?"已暂停":"息屏暂停";JSONObject p=new JSONObject();p.put("paused",true);p.put("frameStatus",status);latest=p.toString();main.post(()->updateUI());}work.postDelayed(this,1000);return;}
  if(screenPaused){recorder.resume();screenPaused=false;hwNs=tempNs=tempPollNs=cpuNs=0;}
  boolean hw=start-hwNs>=config.hardwarePeriod*1_000_000L,temp=start-tempPollNs>=config.tempPeriod*1_000_000L;JSONObject request=new JSONObject();request.put("op","sample");request.put("config",requestConfig);request.put("frames",config.frames);request.put("hardware",hw);request.put("temperatures",temp);JSONObject r=backend.request(request);JSONArray present=r.optJSONArray("present");r.remove("present");Iterator<String> keys=r.keys();while(keys.hasNext()){String k=keys.next();cached.put(k,r.get(k));}
  long now=System.nanoTime();if(hw){hwNs=r.optLong("hardwareSampleNs",now);BatteryManager bm=(BatteryManager)getSystemService(BATTERY_SERVICE);int ua=bm.getIntProperty(BatteryManager.BATTERY_PROPERTY_CURRENT_NOW);double ma=ua==Integer.MIN_VALUE?Double.NaN:ua/1000d;CoreSampler.put(cached,"currentMA",ma);CoreSampler.put(cached,"powerW",voltage>0?Math.abs(ma*voltage/1e6):Double.NaN);cached.put("batteryPct",level);cached.put("voltageMV",voltage>0?voltage:JSONObject.NULL);cached.put("charging",charging);
   long app=android.os.Process.getElapsedCpuTime(),helper=r.optLong("helperCpuMs");boolean separate=backend.uid!=android.os.Process.myUid();double ms=(now-cpuNs)/1e6;CoreSampler.put(cached,"monitorCpuPct",cpuNs>0&&ms>0?Math.max(0,app-appCpu+(separate?helper-helperCpu:0))*100/ms:Double.NaN);cpuNs=now;appCpu=app;helperCpu=helper;
   double rss=Double.NaN;try(BufferedReader rd=new BufferedReader(new InputStreamReader(new FileInputStream("/proc/self/status"),StandardCharsets.UTF_8))){String l;while((l=rd.readLine())!=null)if(l.startsWith("VmRSS:")){rss=Numbers.first(l.substring(6))/1024;break;}}
   CoreSampler.put(cached,"monitorRssMB",rss+(separate?r.optDouble("helperRssMB",0):0));if(Build.VERSION.SDK_INT>=29)cached.put("thermalStatus",power.getCurrentThermalStatus());
  }
  if(temp){tempPollNs=now;tempNs=r.optLong("temperatureSampleNs",now);CoreSampler.put(cached,"batteryC",batteryC);}cached.put("hardwareAgeMs",Math.max(0,(now-hwNs)/1e6));cached.put("temperatureAgeMs",Math.max(0,(now-tempNs)/1e6));cached.put("cycleCostMs",(now-start)/1e6);cached=recorder.append(cached,present,now,config);latest=cached.toString();status=backend.name+" · 记录中";main.post(()->updateUI());long cost=(System.nanoTime()-start)/1_000_000L;work.postDelayed(this,Math.max(config.framePeriod,Math.min(5000,cost+cost/4)));
 }catch(Throwable e){stopRecording(e.toString());}}};
 @Override public void onCreate(){super.onCreate();instance=this;thread=new HandlerThread("lightframe-sampling",android.os.Process.THREAD_PRIORITY_BACKGROUND);thread.start();work=new Handler(thread.getLooper());windows=(WindowManager)getSystemService(WINDOW_SERVICE);registerReceiver(battery,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);nm.createNotificationChannel(new NotificationChannel("monitor","性能记录",NotificationManager.IMPORTANCE_LOW));}
 @Override public int onStartCommand(Intent i,int flags,int id){String a=i==null?"":i.getAction();if("stop".equals(a)){work.post(()->stopRecording(""));return START_NOT_STICKY;}if("pause".equals(a)){paused=!paused;main.post(()->updateUI());return START_NOT_STICKY;}if("hide".equals(a)){hidden=!hidden;main.post(()->updateUI());return START_NOT_STICKY;}if(running)return START_NOT_STICKY;
  running=true;paused=hidden=analyzing=false;stopping=false;status="正在连接采集器…";config=new Config(this);overlayKeys=config.prefs.getString("overlayKeys","fps,frameMs,cpuPct,gpuPct,gpuMHz,cpuC,gpuC,powerW").split(",");sessionPath="";lastOverlayDraw=0;cached=new JSONObject();hwNs=tempNs=tempPollNs=cpuNs=0;startForeground(1,notification());work.post(()->{try{requestConfig=config.json();backend=Backend.connect(this,config.mode);recorder=new SessionRecorder(new File(getFilesDir(),"sessions"),config,backend);sessionPath=recorder.dir.getAbsolutePath();work.post(tick);}catch(Throwable e){stopRecording(e.toString());}});return START_NOT_STICKY;
 }
 private PendingIntent action(String a){return PendingIntent.getService(this,a.hashCode(),new Intent(this,MonitorService.class).setAction(a),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 private Notification notification(){PendingIntent open=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,"monitor").setSmallIcon(R.drawable.ic_stat).setContentTitle("轻帧 · "+status).setContentText("点此查看；停止后自动保存全部数据").setContentIntent(open).setOngoing(true).setOnlyAlertOnce(true).addAction(new Notification.Action.Builder(null,paused?"继续":"暂停",action("pause")).build()).addAction(new Notification.Action.Builder(null,hidden?"显示":"隐藏",action("hide")).build()).addAction(new Notification.Action.Builder(null,"停止并保存",action("stop")).build()).build();}
 private void updateUI(){if(stopping)return;String n=status+paused+hidden;if(!n.equals(notice)){notice=n;((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1,notification());}if(config!=null&&config.overlay&&!hidden&&Settings.canDrawOverlays(this)){if(view==null){view=new Overlay();layout=new WindowManager.LayoutParams(dp(205),WindowManager.LayoutParams.WRAP_CONTENT,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,PixelFormat.TRANSLUCENT);layout.gravity=Gravity.TOP|Gravity.START;layout.x=dp(14);layout.y=dp(90);try{windows.addView(view,layout);}catch(Exception e){view=null;}}if(view!=null&&SystemClock.uptimeMillis()-lastOverlayDraw>=500){lastOverlayDraw=SystemClock.uptimeMillis();view.invalidate();}}else removeOverlay();}
 private void removeOverlay(){if(view!=null){try{windows.removeView(view);}catch(Exception ignored){}view=null;}}
 private void stopRecording(String error){
  if(stopping)return;stopping=true;work.removeCallbacks(tick);paused=false;
  try{if(recorder!=null)recorder.finish(error);}catch(Exception e){error=error+" 保存失败: "+e;}
  if(backend!=null){backend.close();backend=null;}
  try{
   JSONObject last=new JSONObject(cached.toString());last.put("stoppedWhilePaused",new JSONObject(latest).optBoolean("paused",false));last.put("sessionPath",sessionPath);last.put("stoppedUnixMs",System.currentTimeMillis());
   java.nio.file.Path tmp=new File(getFilesDir(),"last-recording-sample.tmp").toPath();
   java.nio.file.Files.write(tmp,last.toString().getBytes(StandardCharsets.UTF_8));
   java.nio.file.Files.move(tmp,new File(getFilesDir(),"last-recording-sample.json").toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);
  }catch(Exception ignored){}
  if(recorder!=null){
   analyzing=true;status="原始记录已保存，正在计算统计…";
   main.post(()->{removeOverlay();((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1,notification());});
   try{
    final long[] reported={0};
    recorder.analyze((rows,frameRows)->{long now=SystemClock.uptimeMillis();if(now-reported[0]>=500){reported[0]=now;status="正在计算记录："+rows+" 次采样 / "+frameRows+" 帧";main.post(()->((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1,notification()));}});
   }catch(Exception e){error=error+" 统计失败（原始记录已保留）: "+e;}
  }
  running=paused=analyzing=false;status=error.isEmpty()?"已保存记录并完成统计":"记录已保存: "+error;
  main.post(()->{removeOverlay();stopForeground(STOP_FOREGROUND_REMOVE);stopSelf();});
 }
 public void diagnose(java.util.function.Consumer<String> done){if(stopping||backend==null){main.post(()->done.accept("采集已停止，请重新导出诊断"));return;}work.post(()->{try{if(stopping||backend==null)throw new IOException("采集已停止，请重新导出诊断");JSONObject r=new JSONObject();r.put("op","diagnose");r.put("frames",false);r.put("config",config.json());String s=backend.request(r).toString(2);main.post(()->done.accept(s));}catch(Exception e){main.post(()->done.accept(e.toString()));}});}
 public void layers(java.util.function.Consumer<String> done){if(stopping||backend==null){main.post(()->done.accept("采集已停止，请重新读取图层"));return;}work.post(()->{try{if(stopping||backend==null)throw new IOException("采集已停止，请重新读取图层");JSONObject r=new JSONObject();r.put("op","layers");String s=backend.request(r).toString();main.post(()->done.accept(s));}catch(Exception e){main.post(()->done.accept(e.toString()));}});}
 @Override public void onDestroy(){running=analyzing=false;instance=null;work.removeCallbacksAndMessages(null);work.post(()->{try{if(recorder!=null)recorder.finish("服务退出");}catch(Exception ignored){}if(backend!=null)backend.close();thread.quitSafely();});removeOverlay();try{unregisterReceiver(battery);}catch(Exception ignored){}super.onDestroy();}
 @Override public IBinder onBind(Intent i){return null;}
 private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 private final class Overlay extends View{
  final Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);float x,y;int ox,oy;long down,lastTap;boolean moved;
  Overlay(){super(MonitorService.this);setContentDescription("轻帧悬浮窗，可拖动，双击打开，长按隐藏");}
  @Override protected void onMeasure(int w,int h){setMeasuredDimension(dp(205),dp(34+overlayKeys.length*20));}
  @Override protected void onDraw(Canvas c){paint.setColor(0xE62A2937);c.drawRoundRect(0,0,getWidth(),getHeight(),dp(10),dp(10),paint);paint.setTypeface(Typeface.DEFAULT);paint.setTextSize(dp(12));paint.setColor(0xFFC7C9FF);c.drawText("轻帧  "+(paused?"已暂停":"记录中"),dp(12),dp(22),paint);try{JSONObject j=new JSONObject(latest);for(int i=0;i<overlayKeys.length;i++){String k=overlayKeys[i],label=Config.label(k).replace("（系统）","").replace("（单核当量）","");paint.setColor(0xFFCCC9D8);paint.setTextSize(dp(10));c.drawText(label,dp(12),dp(43+i*20),paint);paint.setColor(Color.WHITE);paint.setTextAlign(Paint.Align.RIGHT);c.drawText(Config.formatSample(k,j),getWidth()-dp(12),dp(43+i*20),paint);paint.setTextAlign(Paint.Align.LEFT);}}catch(Exception ignored){}}
  @Override public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()==MotionEvent.ACTION_DOWN){x=e.getRawX();y=e.getRawY();ox=layout.x;oy=layout.y;down=SystemClock.uptimeMillis();moved=false;return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){float dx=e.getRawX()-x,dy=e.getRawY()-y;if(Math.abs(dx)+Math.abs(dy)>dp(8))moved=true;android.util.DisplayMetrics m=getResources().getDisplayMetrics();layout.x=Math.max(0,Math.min(m.widthPixels-getWidth(),ox+(int)dx));layout.y=Math.max(0,Math.min(m.heightPixels-getHeight(),oy+(int)dy));try{windows.updateViewLayout(this,layout);}catch(Exception ignored){}return true;}if(e.getAction()==MotionEvent.ACTION_UP&&!moved){long n=SystemClock.uptimeMillis();if(n-down>650){hidden=true;updateUI();}else if(n-lastTap<350){startActivity(new Intent(MonitorService.this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));lastTap=0;}else lastTap=n;performClick();return true;}return true;}
  @Override public boolean performClick(){super.performClick();return true;}
 }
}
